class BookMapper:
    def __init__(self):
        self.dictionary = {
            "gtga": "Geeta Tera Gyan Amrit",
            "Geeta": "Geeta Tera Gyan Amrit",
            "Gita": "Geeta Tera Gyan Amrit",
            "gita": "Geeta Tera Gyan Amrit",
            "geeta": "Geeta Tera Gyan Amrit",
            "Geetha": "Geeta Tera Gyan Amrit",
            "geetha": "Geeta Tera Gyan Amrit",
            "Githa": "Geeta Tera Gyan Amrit",
            "githa": "Geeta Tera Gyan Amrit",
            "ગીતા તારું જ્ઞાન અમૃત": "Geeta Tera Gyan Amrit",
            "ગીતા તારો જ્ઞાન અમૃત": "Geeta Tera Gyan Amrit",
            "ગીતા તારું જ્ઞાન": "Geeta Tera Gyan Amrit",
            "ગીતા તારો જ્ઞાન": "Geeta Tera Gyan Amrit",
            "ગીતા જ્ઞાન": "Geeta Tera Gyan Amrit",
            "Geetha gnana amrutham": "Geeta Tera Gyan Amrit",
            "Geeta Gnana Amrutham": "Geeta Tera Gyan Amrit",
            "geetha gnana amrutham": "Geeta Tera Gyan Amrit",
            "Githa gnana amrutham": "Geeta Tera Gyan Amrit",
            "Githa Gnana Amrutham": "Geeta Tera Gyan Amrit",
            "githa gnana amrutham": "Geeta Tera Gyan Amrit",
            "Geetha nee gnana amrutham": "Geeta Tera Gyan Amrit",
            "Geetha nee Gnana Amrutham": "Geeta Tera Gyan Amrit",
            "geetha nee gnana amrutham": "Geeta Tera Gyan Amrit",
            "Geetha Nee Gnana Amrutham": "Geeta Tera Gyan Amrit",
            "Githa nee gnana amrutham": "Geeta Tera Gyan Amrit",
            "Githa nee Gnana Amrutham": "Geeta Tera Gyan Amrit",
            "Githa Nee Gnana Amrutham": "Geeta Tera Gyan Amrit",
            "githa nee gnana amrutham": "Geeta Tera Gyan Amrit",
            "Geetha ni gnana amrutham": "Geeta Tera Gyan Amrit",
            "Geetha ni Gnana Amrutham": "Geeta Tera Gyan Amrit",
            "Geetha Ni Gnana Amrutham": "Geeta Tera Gyan Amrit",
            "geeth ni gnana amrutham": "Geeta Tera Gyan Amrit",
            "Geetha nee jnaana amrutham": "Geeta Tera Gyan Amrit",
            "Geetha nee Jnana Amrutham": "Geeta Tera Gyan Amrit",
            "geetha nee jnana amrutham": "Geeta Tera Gyan Amrit",
            "Githa nee jnana amrutham": "Geeta Tera Gyan Amrit",
            "Githa nee Jnana Amrutham": "Geeta Tera Gyan Amrit",
            "Githa Nee Jnana Amrutham": "Geeta Tera Gyan Amrit",
            "githa nee jnana amrutham": "Geeta Tera Gyan Amrit",
            "Githa ni jnana amrutham": "Geeta Tera Gyan Amrit",
            "Githa ni Jnana Amrutham": "Geeta Tera Gyan Amrit",
            "Githa Ni Jnana Amrutham": "Geeta Tera Gyan Amrit",
            "githa ni jnana amrutham": "Geeta Tera Gyan Amrit",
            "Githa jnana amrutham": "Geeta Tera Gyan Amrit",
            "Githa Jnana Amrutham": "Geeta Tera Gyan Amrit",
            "githa jnana amrutham": "Geeta Tera Gyan Amrit",
            "Geetha jnana amrutham": "Geeta Tera Gyan Amrit",
            "Geetha Jnana Amrutham": "Geeta Tera Gyan Amrit",
            "geetha jnana amrutham": "Geeta Tera Gyan Amrit",
            "Githa gnana amrutham": "Geeta Tera Gyan Amrit",
            "Githa Gnana Amrutham": "Geeta Tera Gyan Amrit",
            "githa gnana amrutham": "Geeta Tera Gyan Amrit",
            "Bhagavat gita": "Geeta Tera Gyan Amrit",
            "Bhagavat geeta": "Geeta Tera Gyan Amrit",
            "Bhagavat geta": "Geeta Tera Gyan Amrit",
            "Bhagavat Gita": "Geeta Tera Gyan Amrit",
            "bhagavat gita": "Geeta Tera Gyan Amrit",
            "Bhagavat Geeta": "Geeta Tera Gyan Amrit",
            "bhagavat geeta": "Geeta Tera Gyan Amrit",
            "Bhagavad gita": "Geeta Tera Gyan Amrit",
            "Bhagavad Gita": "Geeta Tera Gyan Amrit",
            "bhagavad gita": "Geeta Tera Gyan Amrit",
            "Bhagavad geeta": "Geeta Tera Gyan Amrit",
            "Bhagavad Geeta": "Geeta Tera Gyan Amrit",
            "bhagavad geeta": "Geeta Tera Gyan Amrit",
            "Bhagavat githa": "Geeta Tera Gyan Amrit",
            "Bhagavat Githa": "Geeta Tera Gyan Amrit",
            "bhagavat githa": "Geeta Tera Gyan Amrit",
            "Bhagavat geetha": "Geeta Tera Gyan Amrit",
            "Bhagavat Geetha": "Geeta Tera Gyan Amrit",
            "bhagavat geetha": "Geeta Tera Gyan Amrit",
            "Bhagavath githa": "Geeta Tera Gyan Amrit",
            "Bhagavath Githa": "Geeta Tera Gyan Amrit",
            "bhagavath githa": "Geeta Tera Gyan Amrit",
            "Bhagavath geetha": "Geeta Tera Gyan Amrit",
            "bhagavath geetha": "Geeta Tera Gyan Amrit",
            "Bhagavath Geetha": "Geeta Tera Gyan Amrit",
            "Bhagavatgita": "Geeta Tera Gyan Amrit",
            "bhagavatgita": "Geeta Tera Gyan Amrit",
            "Bhagavatgeeta": "Geeta Tera Gyan Amrit",
            "bhagavatgeeta": "Geeta Tera Gyan Amrit",
            "Bhagavadgita": "Geeta Tera Gyan Amrit",
            "bhagavadgita": "Geeta Tera Gyan Amrit",
            "Bhagavadgeeta": "Geeta Tera Gyan Amrit",
            "bhagavadgeeta": "Geeta Tera Gyan Amrit",
            "Bhagawatgita": "Geeta Tera Gyan Amrit",
            "bhagawadgita": "Geeta Tera Gyan Amrit",
            "Bhagawatgeeta": "Geeta Tera Gyan Amrit",
            "bhagawatgeeta": "Geeta Tera Gyan Amrit",
            "Bhagawadgita": "Geeta Tera Gyan Amrit",
            "bhagawadgita": "Geeta Tera Gyan Amrit",
            "Bhagawadgeeta": "Geeta Tera Gyan Amrit",
            "bhagawadgeeta": "Geeta Tera Gyan Amrit",
            "Bhagavathgitha": "Geeta Tera Gyan Amrit",
            "bhagavathgitha": "Geeta Tera Gyan Amrit",
            "Bhagavathgeetha": "Geeta Tera Gyan Amrit",
            "bhagavathgeetha": "Geeta Tera Gyan Amrit",
            "Bhagavdgitha": "Geeta Tera Gyan Amrit",
            "bhagavadgitha": "Geeta Tera Gyan Amrit",
            "Bhagavadgeetha": "Geeta Tera Gyan Amrit",
            "bhagavadgeetha": "Geeta Tera Gyan Amrit",
            "Bhagawadgitha": "Geeta Tera Gyan Amrit",
            "bhagawadgitha": "Geeta Tera Gyan Amrit",
            "Bhagawadgeetha": "Geeta Tera Gyan Amrit",
            "bhagawadgeetha": "Geeta Tera Gyan Amrit",
            "Bhagawad gita": "Geeta Tera Gyan Amrit",
            "Bhagawad Gita": "Geeta Tera Gyan Amrit",
            "bhagawad gita": "Geeta Tera Gyan Amrit",
            "Bhagawad geeta": "Geeta Tera Gyan Amrit",
            "Bhagawad Geeta": "Geeta Tera Gyan Amrit",
            "bhagawad geeta": "Geeta Tera Gyan Amrit",
            "Bhagawad githa": "Geeta Tera Gyan Amrit",
            "Bhagawad Githa": "Geeta Tera Gyan Amrit",
            "bhagawad githa": "Geeta Tera Gyan Amrit",
            "Bhagawad geetha": "Geeta Tera Gyan Amrit",
            "Bhagawad Geetha": "Geeta Tera Gyan Amrit",
            "bhagawad geetha": "Geeta Tera Gyan Amrit",
            "GTGA": "Geeta Tera Gyan Amrit",
            "gg": "Gyan Ganga",
            "Jnana ganga": "Gyan Ganga",
            "Jnana Ganga": "Gyan Ganga",
            "jnana ganga": "Gyan Ganga",
            "Gnana Ganga": "Gyan Ganga",
            "Gnana ganga": "Gyan Ganga",
            "gnana ganga": "Gyan Ganga",
            "GG": "Gyan Ganga",
            "jkr": "Jeene Ki Raah",
            "Jeevinchu margamu": "Jeene Ki Raah",
            "jeevinchu margamu": "Jeene Ki Raah",
            "Jeevinchu Margamu": "Jeene Ki Raah",
            "Jivinchu margamu": "Jeene Ki Raah",
            "jivinchu margamu": "Jeene Ki Raah",
            "Jivinchu Margamu": "Jeene Ki Raah",
            "Jeevinchu margam": "Jeene Ki Raah",
            "jeevinchu margam": "Jeene Ki Raah",
            "Jeevinchu Margam": "Jeene Ki Raah",
            "Jivinchu margam": "Jeene Ki Raah",
            "jivinchu margam": "Jeene Ki Raah",
            "Jivinchu Margam": "Jeene Ki Raah",
            "Geevinchu margamu": "Jeene Ki Raah",
            "geevinchu margamu": "Jeene Ki Raah",
            "Geevinchu Margamu": "Jeene Ki Raah",
            "Givinchu margamu": "Jeene Ki Raah",
            "givinchu margamu": "Jeene Ki Raah",
            "Givinchu Margamu": "Jeene Ki Raah",
            "Geevinchu margam": "Jeene Ki Raah",
            "geevinchu margam": "Jeene Ki Raah",
            "Geevinchu Margam": "Jeene Ki Raah",
            "Givinchu margam": "Jeene Ki Raah",
            "givinchu margam": "Jeene Ki Raah",
            "Givinchu Margam": "Jeene Ki Raah",
            "JEEVINCHU MARGAMU": "Jeene Ki Raah",
            "JEEVINCHU MARGAM": "Jeene Ki Raah",
            "JIVINCHU MARGAMU": "Jeene Ki Raah",
            "JIVINCHU MARGAM": "Jeene Ki Raah",
            "JEEVINCHUMARGAMU": "Jeene Ki Raah",
            "JEEVINCHUMARGAM": "Jeene Ki Raah",
            "JIVINCHUMARGAMU": "Jeene Ki Raah",
            "JIVINCHUMARGAM": "Jeene Ki Raah",
            "Jevinchu margamu": "Jeene Ki Raah",
            "jevinchu margamu": "Jeene Ki Raah",
            "Jevinchu Margamu": "Jeene Ki Raah",
            "Jevinchu margam": "Jeene Ki Raah",
            "jevinchu margam": "Jeene Ki Raah",
            "Jevinchu Margam": "Jeene Ki Raah",
            "Jivinchu maargamu": "Jeene Ki Raah",
            "jivinchu maargamu": "Jeene Ki Raah",
            "Jivinchu Maargamu": "Jeene Ki Raah",
            "Jevinchu maargam": "Jeene Ki Raah",
            "jevinchu maargam": "Jeene Ki Raah",
            "Jevinchu Maargam": "Jeene Ki Raah",
            "Jivinchu maargam": "Jeene Ki Raah",
            "jivinchu maargam": "Jeene Ki Raah",
            "Jivinchu Maargam": "Jeene Ki Raah",
            "Jeevinchu maargamu": "Jeene Ki Raah",
            "jeevinchu maargamu": "Jeene Ki Raah",
            "Jeevinchu Maargamu": "Jeene Ki Raah",
            "Jivinchu maargamu": "Jeene Ki Raah",
            "jivinchu maargamu": "Jeene Ki Raah",
            "Jivinchu Maargamu": "Jeene Ki Raah",
            "Jeevinchu maargam": "Jeene Ki Raah",
            "jeevinchu maargam": "Jeene Ki Raah",
            "Jeevinchu Maargam": "Jeene Ki Raah",
            "Jivinchu maargam": "Jeene Ki Raah",
            "jivinchu maargam": "Jeene Ki Raah",
            "Jivinchu Maargam": "Jeene Ki Raah",
            "JKR": "Jeene Ki Raah"
        }

    def get_book_from_address_record(self, address_string):
        if len(address_string) > 0:
            for book_name in self.dictionary:
                if address_string.find(book_name) != -1:
                    return self.dictionary[book_name]
