class StateMapper:
    def __init__(self):
        self.dictionary = {
            "ANDAMAN": "ANDAMAN",
            "Andaman": "ANDAMAN",
            "Nicobar": "ANDAMAN",
            "अंडमान": "ANDAMAN",
            "निकोबार": "ANDAMAN",
            "VISAKHAPATNAM": "ANDAMAN",
            "Andaman": "ANDAMAN",

            "ANDRA PRADESH": "ANDRA PRADESH",
            "SRIKAKULAM": "ANDRA PRADESH",
            "EAST GODAVARI": "ANDRA PRADESH",
            "WEST GODAVARI": "ANDRA PRADESH",
            "Warangal": "ANDRA PRADESH",
            "Kovvur": "ANDRA PRADESH",
            "Andhra Pradesh": "ANDRA PRADESH",
            "विशाखापत्तनम": "ANDRA PRADESH",
            "पूर्व गोड़वारी": "ANDRA PRADESH",
            "पश्चिम गोडावरी": "ANDRA PRADESH",
            "वारंगल": "ANDRA PRADESH",
            "आंध्र प्रदेश": "ANDRA PRADESH",

            "ARUNACHAL PRADESH": "ARUNACHAL PRADESH",
            "Arunachal": "ARUNACHAL PRADESH",
            "अरुणाचल": "ARUNACHAL PRADESH",

            "ASSAM": "ASSAM",
            "NALBARI": "ASSAM",
            "BARPETA": "ASSAM",
            "KOKRAJHAR": "ASSAM",
            "DIBRUGARH": "ASSAM",
            "Assam": "ASSAM",
            "Nalbari": "ASSAM",
            "barpeta": "ASSAM",
            "kokrajhar": "ASSAM",
            "dibrugarh": "ASSAM",
            "ASSAM": "ASSAM",
            "nalbari": "ASSAM",
            "barpeta": "ASSAM",
            "kokrajhar": "ASSAM",
            "dibrugarh": "ASSAM",
            "assam": "ASSAM",
            "डिब्रुगार": "ASSAM",
            "आसाम": "ASSAM",

            "BIHAR": "BIHAR",
            "Arrah": "BIHAR",
            "Bhabua": "BIHAR",
            "BHOJPUR": "BIHAR",
            "BUXAR": "BIHAR",
            "DARBHANGA": "BIHAR",
            "EAST CHAMPARAN": "BIHAR",
            "NALANDA": "BIHAR",
            "Nardiganj": "BIHAR",
            "Narkatia": "BIHAR",
            "WEST CHAMPARAN": "BIHAR",
            "bhabua": "BIHAR",
            "darbhanga": "BIHAR",
            "east champaran": "BIHAR",
            "nalanda": "BIHAR",
            "west champaran": "BIHAR",
            "दरभंगा": "BIHAR",
            "नरकटिया": "BIHAR",
            "नारदीगंज": "BIHAR",
            "पश्चिम चंपारण": "BIHAR",
            "पूर्व चम्पारण": "BIHAR",
            "SAMASTIPUR": "BIHAR",
            "samastipur": "BIHAR",
            "Samastipur": "BIHAR",
            "saharsa": "BIHAR",
            "Saharsa": "BIHAR",
            "SAHARSA": "BIHAR",
            "सहरसा": "BIHAR",
            "गया बिहार": "BIHAR",
            "Madhubani": "BIHAR",
            "Madhepura": "BIHAR",
            "पटना बिहार": "BIHAR",
            "Rohtas Sasaram": "BIHAR",
            "sasaram bihar": "BIHAR",
            "rohtas bihar": "BIHAR",
            "siwan Bihar": "BIHAR",
            "मुंगेर बिहार": "BIHAR",
            "GOPALGANJ BIHAR": "BIHAR",
            "Samastipur Bihar": "BIHAR",
            "purnea bihar": "BIHAR",
            "SARAN BIHAR": "BIHAR",
            "saran bihar": "BIHAR",
            "Saran Bihar": "BIHAR",
            "CHAPRA BIHAR": "BIHAR",
            "chapra bihar": "BIHAR",
            "Chapra Bihar": "BIHAR",
            "Sitamarhi Bihar": "BIHAR",
            "Araria Bihar": "BIHAR",
            "jila Bhagalpur": "BIHAR",
            "जिला बेगूसराय": "BIHAR",
            "dist Sitamarhi": "BIHAR",
            "district khagaria": "BIHAR",
            "District rohtas": "BIHAR",
            "araria bihar": "BIHAR",
            "ARARIA BIHAR": "BIHAR",
            "Araria Bihar": "BIHAR",
            "Araria bihar": "BIHAR",
            "aurangabad bihar": "BIHAR",
            "AURANGABAD BIHAR": "BIHAR",
            "Aurangabad Bihar": "BIHAR",
            "Aurangabad bihar": "BIHAR",
            "dist araria bihar": "BIHAR",
            "DIST ARARIA BIHAR": "BIHAR",
            "Dist Araria Bihar": "BIHAR",
            "Dist araria bihar": "BIHAR",
            "dist banka": "BIHAR",
            "DIST BANKA": "BIHAR",
            "Dist Banka": "BIHAR",
            "Dist banka": "BIHAR",
            "dist jamui": "BIHAR",
            "DIST JAMUI": "BIHAR",
            "Dist Jamui": "BIHAR",
            "Dist jamui": "BIHAR",
            "dist patna": "BIHAR",
            "DIST PATNA": "BIHAR",
            "Dist Patna": "BIHAR",
            "Dist patna": "BIHAR",
            "dist rohtas": "BIHAR",
            "DIST ROHTAS": "BIHAR",
            "Dist Rohtas": "BIHAR",
            "Dist rohtas": "BIHAR",
            "dist sitamarhi": "BIHAR",
            "DIST SITAMARHI": "BIHAR",
            "Dist Sitamarhi": "BIHAR",
            "Dist sitamarhi": "BIHAR",
            "district banka": "BIHAR",
            "DISTRICT BANKA": "BIHAR",
            "District Banka": "BIHAR",
            "District banka": "BIHAR",
            "district bettiah": "BIHAR",
            "DISTRICT BETTIAH": "BIHAR",
            "District Bettiah": "BIHAR",
            "District bettiah": "BIHAR",
            "district kaimur": "BIHAR",
            "DISTRICT KAIMUR": "BIHAR",
            "District Kaimur Bhabhua": "BIHAR",
            "District Bhabhua": "BIHAR",
            "district khagaria": "BIHAR",
            "DISTRICT KHAGARIA": "BIHAR",
            "District Khagaria": "BIHAR",
            "District khagaria": "BIHAR",
            "district rohtas": "BIHAR",
            "DISTRICT ROHTAS": "BIHAR",
            "District Rohtas": "BIHAR",
            "District rohtas": "BIHAR",
            "jila bhagalpur": "BIHAR",
            "JILA BHAGALPUR": "BIHAR",
            "Jila Bhagalpur": "BIHAR",
            "Jila bhagalpur": "BIHAR",
            "जिला लखीसराय": "BIHAR",
            "sitamarhi bihar": "BIHAR",
            "SITAMARHI BIHAR": "BIHAR",
            "Sitamarhi Bihar": "BIHAR",
            "Sitamarhi bihar": "BIHAR",
            "जिला बेगुसराय": "BIHAR",
            "जिला बेगूसराय": "BIHAR",
            "जिला मुजफ्फरपुर बिहार": "BIHAR",

            "CHATTISHGARH": "CHATTISHGARH",
            "MAHASAMUND": "CHATTISHGARH",
            "BALOD BAZER": "CHATTISHGARH",
            "DHAMTARI": "CHATTISHGARH",
            "Dantewada": "CHATTISHGARH",
            "JANJGIRCHAMPA": "CHATTISHGARH",
            "Janjgir-Champa": "CHATTISHGARH",
            "SURGUJA": "CHATTISHGARH",
            "Chattisgarh": "CHATTISHGARH",
            "Mahasamund": "CHATTISHGARH",
            "balod bazer": "CHATTISHGARH",
            "dhamtari": "CHATTISHGARH",
            "dantewada": "CHATTISHGARH",
            "janjgirchampa": "CHATTISHGARH",
            "janjgir-champa": "CHATTISHGARH",
            "jaspur": "CHATTISHGARH",
            "surguja": "CHATTISHGARH",
            "chattisgarh": "CHATTISHGARH",
            "mahasamund": "CHATTISHGARH",
            "balod bazer": "CHATTISHGARH",
            "dhamtari": "CHATTISHGARH",
            "dantewada": "CHATTISHGARH",
            "janjgirchampa": "CHATTISHGARH",
            "janjgir-champa": "CHATTISHGARHCHATTISHGARH",
            "surguja": "CHATTISHGARH",
            "chattisgarh": "CHATTISHGARH",
            "छत्तीसगड": "CHATTISHGARH",
            "Raipur Chhattisgarh": "CHATTISHGARH",
            "dist korba": "CHATTISHGARH",
            "DIST KORBA": "CHATTISHGARH",
            "Dist Korba": "CHATTISHGARH",
            "Dist korba": "CHATTISHGARH",
            "जिला बालोद": "CHATTISHGARH",

            "DELHI": "DELHI",
            "दिल्ली": "DELHI",
            "DELHI": "DELHI",
            "Delhi": "DELHI",
            "A2": "DELHI",
            "Delhi": "DELHI",

            "GOA": "GOA",
            "goa": "GOA",
            "GOA": "GOA",
            "Goa": "GOA",

            "GUJRAT": "GUJRAT",
            "Ahmedabad City East": "GUJRAT",
            "Ahmedabad City West": "GUJRAT",
            "GUJRAT": "GUJRAT",
            "Gujrat": "GUJRAT",
            "gujrat": "GUJRAT",
            "banaskatha": "GUJRAT",
            "Bharuch": "GUJRAT",
            "Bhavnagar": "GUJRAT",
            "Chanasma": "GUJRAT",
            "Dev Bhumi Dwarka": "GUJRAT",
            "Gandhinagar": "GUJRAT",
            "Gir Somnath": "GUJRAT",
            "Jamnagar": "GUJRAT",
            "Junagadh": "GUJRAT",
            "Junagadh Rural": "GUJRAT",
            "Mehsana": "GUJRAT",
            "Patan": "GUJRAT",
            "Porbandar": "GUJRAT",
            "Rajkot": "GUJRAT",
            "Sabarkantha": "GUJRAT",
            "Silvassa": "GUJRAT",
            "Surat": "GUJRAT",
            "Surendranagar": "GUJRAT",
            "Vadodara": "GUJRAT",
            "अहमदाबाद": "GUJRAT",
            "गिर सोमनाथ": "GUJRAT",
            "जामनगर": "GUJRAT",
            "पाटन": "GUJRAT",
            "वडोदरा": "GUJRAT",
            "सिलवासा": "GUJRAT",
            "અંકલેશ્વર": "GUJRAT",
            "અંજાર": "GUJRAT",
            "અબડાસા": "GUJRAT",
            "અમદાવાદ સિટી ઇસ્ટ": "GUJRAT",
            "અમદાવાદ સિટી વેસ્ટ": "GUJRAT",
            "અમરેલી": "GUJRAT",
            "અમીરગઢ": "GUJRAT",
            "અરવલ્લી": "GUJRAT",
            "આંકલાવ": "GUJRAT",
            "આણંદ": "GUJRAT",
            "આમોદ": "GUJRAT",
            "આહવા": "GUJRAT",
            "ઇડર": "GUJRAT",
            "ઉચ્છલ": "GUJRAT",
            "ઉના": "GUJRAT",
            "ઉપલેટા": "GUJRAT",
            "ઉમરગામ": "GUJRAT",
            "ઉમરપાડા": "GUJRAT",
            "ઉમરાળા": "GUJRAT",
            "ઉમરેઠ": "GUJRAT",
            "ઊંઝા": "GUJRAT",
            "ઓખામંડળ": "GUJRAT",
            "ઓલપાડ": "GUJRAT",
            "કચ્છ": "GUJRAT",
            "કઠલાલ": "GUJRAT",
            "કડાણા": "GUJRAT",
            "કડી": "GUJRAT",
            "કપડવંજ": "GUJRAT",
            "કપરાડા": "GUJRAT",
            "કરજણ": "GUJRAT",
            "કલોલ": "GUJRAT",
            "કલ્યાણપુર": "GUJRAT",
            "કવાંટ": "GUJRAT",
            "કાંકરેજ": "GUJRAT",
            "કામરેજ": "GUJRAT",
            "કાલાવડ": "GUJRAT",
            "કાલોલ": "GUJRAT",
            "કુંકાવાવ વડીયા": "GUJRAT",
            "કુકરમુંડા": "GUJRAT",
            "કુતિયાણા": "GUJRAT",
            "કેન્દ્રશાસિત પ્રદેશ": "GUJRAT",
            "કેશોદ": "GUJRAT",
            "કોટડા સાંગાણી": "GUJRAT",
            "કોડિનાર": "GUJRAT",
            "ખંભાત": "GUJRAT",
            "ખંભાળીયા": "GUJRAT",
            "ખાંભા": "GUJRAT",
            "ખાનપુર": "GUJRAT",
            "ખેડબ્રહ્મા": "GUJRAT",
            "ખેડા": "GUJRAT",
            "ખેરગામ": "GUJRAT",
            "ખેરાલુ": "GUJRAT",
            "ગઢડા": "GUJRAT",
            "ગણદેવી": "GUJRAT",
            "ગરબાડા": "GUJRAT",
            "ગરીયાધાર": "GUJRAT",
            "ગરૂડેશ્વર": "GUJRAT",
            "ગળતેશ્વર": "GUJRAT",
            "ગાંધીધામ": "GUJRAT",
            "ગાંધીનગર": "GUJRAT",
            "ગીર સોમનાથ": "GUJRAT",
            "ગીર-ગઢડા": "GUJRAT",
            "ગોંડલ": "GUJRAT",
            "ગોઝારીયા": "GUJRAT",
            "ગોધરા": "GUJRAT",
            "ઘોઘંબા": "GUJRAT",
            "ઘોઘા": "GUJRAT",
            "ચાણસ્મા": "GUJRAT",
            "ચીખલી": "GUJRAT",
            "ચુડા": "GUJRAT",
            "ચોટીલા": "GUJRAT",
            "ચોર્યાસી": "GUJRAT",
            "છોટા ઉદેપુર": "GUJRAT",
            "જંબુસર": "GUJRAT",
            "જલાલપોર": "GUJRAT",
            "જસદણ": "GUJRAT",
            "જાંબુઘોડા": "GUJRAT",
            "જાફરાબાદ": "GUJRAT",
            "જામકંડોરણા": "GUJRAT",
            "જામજોધપુર": "GUJRAT",
            "જામનગર": "GUJRAT",
            "જુનાગઢ ગ્રામીણ": "GUJRAT",
            "જૂનાગઢ શહેર": "GUJRAT",
            "જેતપુર": "GUJRAT",
            "જેતપુર પાવી": "GUJRAT",
            "જેસર": "GUJRAT",
            "જોટાણા": "GUJRAT",
            "જોડીયા": "GUJRAT",
            "ઝઘડીયા": "GUJRAT",
            "ઝાલોદ": "GUJRAT",
            "ટંકારા": "GUJRAT",
            "ઠાસરા": "GUJRAT",
            "ડભોઇ": "GUJRAT",
            "ડાંગ": "GUJRAT",
            "ડીસા": "GUJRAT",
            "ડેડીયાપાડા": "GUJRAT",
            "ડેસર": "GUJRAT",
            "ડોલવણ": "GUJRAT",
            "તલોદ": "GUJRAT",
            "તળાજા": "GUJRAT",
            "તાપી": "GUJRAT",
            "તારાપુર": "GUJRAT",
            "તાલાલા": "GUJRAT",
            "તિલકવાડા": "GUJRAT",
            "થરાદ": "GUJRAT",
            "થાનગઢ": "GUJRAT",
            "દમણ": "GUJRAT",
            "દસાડા": "GUJRAT",
            "દસ્ક્રોઈ": "GUJRAT",
            "દહેગામ": "GUJRAT",
            "દાંતા": "GUJRAT",
            "દાંતીવાડા": "GUJRAT",
            "દાહોદ": "GUJRAT",
            "દિયોદર": "GUJRAT",
            "દીવ": "GUJRAT",
            "દેત્રોજ-રામપુરા": "GUJRAT",
            "દેવ ભૂમિ દ્વારકા": "GUJRAT",
            "દેવગઢ બારિયા": "GUJRAT",
            "ધંધુકા": "GUJRAT",
            "ધનસુરા": "GUJRAT",
            "ધરમપુર": "GUJRAT",
            "ધાનપુર": "GUJRAT",
            "ધાનેરા": "GUJRAT",
            "ધારી": "GUJRAT",
            "ધોરાજી": "GUJRAT",
            "ધોલેરા": "GUJRAT",
            "ધોળકા": "GUJRAT",
            "ધ્રાંગધ્રા": "GUJRAT",
            "ધ્રોલ": "GUJRAT",
            "નખત્રાણા": "GUJRAT",
            "નડિયાદ": "GUJRAT",
            "નર્મદા": "GUJRAT",
            "નવસારી": "GUJRAT",
            "નસવાડી": "GUJRAT",
            "નાંદોદ": "GUJRAT",
            "નિઝર": "GUJRAT",
            "નેત્રંગ": "GUJRAT",
            "પંચમહાલ": "GUJRAT",
            "પડધરી": "GUJRAT",
            "પલસાણા": "GUJRAT",
            "પાટણ": "GUJRAT",
            "પાટણ-વેરાવળ": "GUJRAT",
            "પાદરા": "GUJRAT",
            "પારડી": "GUJRAT",
            "પાલનપુર": "GUJRAT",
            "પાલીતાણા": "GUJRAT",
            "પેટલાદ": "GUJRAT",
            "પોરબંદર": "GUJRAT",
            "પોશીના": "GUJRAT",
            "પ્રાંતિજ": "GUJRAT",
            "ફતેપુરા": "GUJRAT",
            "બગસરા": "GUJRAT",
            "બનાસકાંઠા": "GUJRAT",
            "બરવાળા": "GUJRAT",
            "બરોડા": "GUJRAT",
            "બાબરા": "GUJRAT",
            "બાયડ": "GUJRAT",
            "બારડોલી": "GUJRAT",
            "બાલાસિનોર": "GUJRAT",
            "બાવલા": "GUJRAT",
            "બેચરાજી": "GUJRAT",
            "બોટાદ": "GUJRAT",
            "બોડેલી": "GUJRAT",
            "બોરસદ": "GUJRAT",
            "ભચાઉ": "GUJRAT",
            "ભરૂચ": "GUJRAT",
            "ભાણવડ": "GUJRAT",
            "ભાભર": "GUJRAT",
            "ભાવનગર": "GUJRAT",
            "ભીલોડા": "GUJRAT",
            "ભુજ": "GUJRAT",
            "ભેસાણ": "GUJRAT",
            "મંડળ": "GUJRAT",
            "મહીસાગર": "GUJRAT",
            "મહુધા": "GUJRAT",
            "મહુવા": "GUJRAT",
            "મહુવા": "GUJRAT",
            "મહેમદાબાદ": "GUJRAT",
            "મહેસાણા": "GUJRAT",
            "માંગરોળ": "GUJRAT",
            "માંગરોળ": "GUJRAT",
            "માંડવી": "GUJRAT",
            "માંડવી": "GUJRAT",
            "માણસા": "GUJRAT",
            "માણાવદર": "GUJRAT",
            "માતર": "GUJRAT",
            "માલપુર": "GUJRAT",
            "માળીયા મિયાણા": "GUJRAT",
            "માળીયા હાટીના": "GUJRAT",
            "મુન્દ્રા": "GUJRAT",
            "મૂળી": "GUJRAT",
            "મેંદરડા": "GUJRAT",
            "મેઘરાજ": "GUJRAT",
            "મોડાસા": "GUJRAT",
            "મોરબી": "GUJRAT",
            "મોરવા હડફ": "GUJRAT",
            "રાજકોટ": "GUJRAT",
            "રાજપીપળા": "GUJRAT",
            "રાજુલા": "GUJRAT",
            "રાણપુર": "GUJRAT",
            "રાણાવાવ": "GUJRAT",
            "રાધનપુર": "GUJRAT",
            "રાપર": "GUJRAT",
            "લખતર": "GUJRAT",
            "લખપત": "GUJRAT",
            "લાખણી": "GUJRAT",
            "લાઠી": "GUJRAT",
            "લાલપુર": "GUJRAT",
            "લીંબડી": "GUJRAT",
            "લીમખેડા": "GUJRAT",
            "લીલીયા": "GUJRAT",
            "લુણાવાડા": "GUJRAT",
            "લોધીકા": "GUJRAT",
            "વંથલી": "GUJRAT",
            "વઘઇ": "GUJRAT",
            "વડગામ": "GUJRAT",
            "વડનગર": "GUJRAT",
            "વડાલી": "GUJRAT",
            "વડોદરા (બરોડા": "GUJRAT",
            "વઢવાણ": "GUJRAT",
            "વલસાડ": "GUJRAT",
            "વલ્લભીપુર": "GUJRAT",
            "વસો": "GUJRAT",
            "વાંકાનેર": "GUJRAT",
            "વાંસદા": "GUJRAT",
            "વાગરા": "GUJRAT",
            "વાઘોડિયા": "GUJRAT",
            "વાપી": "GUJRAT",
            "વાલિયા": "GUJRAT",
            "વાલોડ": "GUJRAT",
            "વાવ": "GUJRAT",
            "વિંચીયા": "GUJRAT",
            "વિજયનગર": "GUJRAT",
            "વિજાપુર": "GUJRAT",
            "વિરમગામ": "GUJRAT",
            "વિસનગર": "GUJRAT",
            "વિસાવદર": "GUJRAT",
            "વીરપુર": "GUJRAT",
            "વ્યારા": "GUJRAT",
            "શંખેશ્વર": "GUJRAT",
            "શહેરા": "GUJRAT",
            "શિનોર": "GUJRAT",
            "સંખેડા": "GUJRAT",
            "સંજેલી": "GUJRAT",
            "સંતરામપુર": "GUJRAT",
            "સતલાસણા": "GUJRAT",
            "સમી": "GUJRAT",
            "સરસ્વતી": "GUJRAT",
            "સાંતલપુર": "GUJRAT",
            "સાગબારા": "GUJRAT",
            "સાણંદ": "GUJRAT",
            "સાબરકાંઠા": "GUJRAT",
            "સાયલા": "GUJRAT",
            "સાવરકુંડલા": "GUJRAT",
            "સાવલી": "GUJRAT",
            "સિંગવડ": "GUJRAT",
            "સિદ્ધપુર": "GUJRAT",
            "સિલવાસા": "GUJRAT",
            "સિહોર": "GUJRAT",
            "સુઇગામ": "GUJRAT",
            "સુત્રાપાડા": "GUJRAT",
            "સુબીર": "GUJRAT",
            "સુરત": "GUJRAT",
            "સુરેન્દ્રનગર": "GUJRAT",
            "સોજીત્રા": "GUJRAT",
            "સોનગઢ": "GUJRAT",
            "હળવદ": "GUJRAT",
            "હાંસોટ": "GUJRAT",
            "હારિજ": "GUJRAT",
            "હાલોલ": "GUJRAT",
            "હિંમતનગર": "GUJRAT",
            "Daman": "GUJRAT",
            "Diu": "GUJRAT",
            "Dadra": "GUJRAT",
            "Nagari": "GUJRAT",
            "Ahmedabad": "GUJRAT",
            "BANASKANTHA": "GUJRAT",
            "banaskantha": "GUJRAT",
            "Banaskantha": "GUJRAT",
            "Godhra PANCHMAHAL": "GUJRAT",
            "Di anand": "GUJRAT",
            "ta gandhidham": "GUJRAT",
            "kutchh": "GUJRAT",
            "dist mahesana": "GUJRAT",
            "Dist Morbi": "GUJRAT",
            "di anand": "GUJRAT",
            "DI ANAND": "GUJRAT",
            "Di Anand": "GUJRAT",
            "Di anand": "GUJRAT",
            "dist baroda": "GUJRAT",
            "DIST BARODA": "GUJRAT",
            "Dist Baroda": "GUJRAT",
            "Dist baroda": "GUJRAT",
            "dist mahesana": "GUJRAT",
            "DIST MAHESANA": "GUJRAT",
            "Dist Mahesana": "GUJRAT",
            "Dist mahesana": "GUJRAT",
            "dist mahisagar": "GUJRAT",
            "DIST MAHISAGAR": "GUJRAT",
            "Dist Mahisagar": "GUJRAT",
            "Dist mahisagar": "GUJRAT",
            "dist morbi": "GUJRAT",
            "DIST MORBI": "GUJRAT",
            "Dist Morbi": "GUJRAT",
            "Dist morbi": "GUJRAT",
            "dist panchmahal": "GUJRAT",
            "DIST PANCHMAHAL": "GUJRAT",
            "Dist Panchmahal": "GUJRAT",
            "Dist panchmahal": "GUJRAT",
            "dist navsari": "GUJRAT",
            "DIST NAVSARI": "GUJRAT",
            "Dist Navsari": "GUJRAT",
            "Dist navsari": "GUJRAT",
            "godhra panchmahal": "GUJRAT",
            "GODHRA PANCHMAHAL": "GUJRAT",
            "Godhra Panchmahal": "GUJRAT",
            "Godhra panchmahal": "GUJRAT",
            "panchmhal": "GUJRAT",
            "PANCHMHAL": "GUJRAT",
            "Panchmhal": "GUJRAT",
            "Panchmhal": "GUJRAT",
            "ta gandhidham": "GUJRAT",
            "TA GANDHIDHAM": "GUJRAT",
            "Ta Gandhidham": "GUJRAT",
            "Ta gandhidham kutchh": "GUJRAT",

            "HARYANA": "HARYANA",
            "FARIDABAD": "HARYANA",
            "GURGAON": "HARYANA",
            "MEWAT": "HARYANA",
            "FATEHABAD": "HARYANA",
            "MAHENDRAGARH": "HARYANA",
            "REWARI": "HARYANA",
            "ROHTAK": "HARYANA",
            "JHAJJAR": "HARYANA",
            "HISAR": "HARYANA",
            "SIRSA": "HARYANA",
            "JIND": "HARYANA",
            "KARNAL": "HARYANA",
            "BHIWANI": "HARYANA",
            "SONIPAT": "HARYANA",
            "PANIPAT": "HARYANA",
            "AMBALA": "HARYANA",
            "YAMUNANAGAR": "HARYANA",
            "PANCHKULA": "HARYANA",
            "KURUKSHETRA": "HARYANA",
            "KAITHAL": "HARYANA",
            "Faridabad": "HARYANA",
            "gurgaon": "HARYANA",
            "mewat": "HARYANA",
            "fatehabad": "HARYANA",
            "mahendragarh": "HARYANA",
            "rewari": "HARYANA",
            "rohtak": "HARYANA",
            "jhajjar": "HARYANA",
            "hisar": "HARYANA",
            "sirsa": "HARYANA",
            "jind": "HARYANA",
            "karnal": "HARYANA",
            "bhiwani": "HARYANA",
            "sonipat": "HARYANA",
            "panipat": "HARYANA",
            "ambala": "HARYANA",
            "yamunanagar": "HARYANA",
            "panchkula": "HARYANA",
            "kurukshetra": "HARYANA",
            "kaithal": "HARYANA",
            "faridabad": "HARYANA",
            "gurgaon": "HARYANA",
            "mewat": "HARYANA",
            "fatehabad": "HARYANA",
            "mahendragarh": "HARYANA",
            "rewari": "HARYANA",
            "rohtak": "HARYANA",
            "jhajjar": "HARYANA",
            "hisar": "HARYANA",
            "sirsa": "HARYANA",
            "jind": "HARYANA",
            "karnal": "HARYANA",
            "bhiwani": "HARYANA",
            "sonipat": "HARYANA",
            "panipat": "HARYANA",
            "ambala": "HARYANA",
            "yamunanagar": "HARYANA",
            "panchkula": "HARYANA",
            "kurukshetra": "HARYANA",
            "kaithal": "HARYANA",
            "Haryana": "HARYANA",
            "HARYANA": "HARYANA",
            "फरीदाबाद": "HARYANA",
            "गुरगाव": "HARYANA",
            "मावेट": "HARYANA",
            "फतेहाबाद": "HARYANA",
            "महेंद्रगर": "HARYANA",
            "रिवेरी": "HARYANA",
            "रोहतक": "HARYANA",
            "झज्जर": "HARYANA",
            "हिसार": "HARYANA",
            "सिरसा": "HARYANA",
            "जिंद": "HARYANA",
            "कार्नल": "HARYANA",
            "भिवानी": "HARYANA",
            "सोनीपॅट": "HARYANA",
            "पानिपॅट": "HARYANA",
            "अंबाला": "HARYANA",
            "यमुनानगर": "HARYANA",
            "पंचकुला": "HARYANA",
            "कुरुक्षेत्र": "HARYANA",
            "कैथल": "HARYANA",
            "हरियाणा": "HARYANA",
            "Fridabad": "HARYANA",
            "fridabad": "HARYANA",
            "FRIDABAD": "HARYANA",
            "Fridabad": "HARYANA",
            "Fridabad": "HARYANA",

            "HIMCHAL PRADESH": "HIMCHAL PRADESH",
            "SHIMLA": "HIMCHAL PRADESH",
            "SOLAN": "HIMCHAL PRADESH",
            "KULLU": "HIMCHAL PRADESH",
            "KINNAUR": "HIMCHAL PRADESH",
            "LAHUL": "HIMCHAL PRADESH",
            "SIRMAUR": "HIMCHAL PRADESH",
            "KANGRA": "HIMCHAL PRADESH",
            "CHAMBA": "HIMCHAL PRADESH",
            "Himachal": "HIMCHAL PRADESH",
            "Shimla": "HIMCHAL PRADESH",
            "Solan": "HIMCHAL PRADESH",
            "Kullu": "HIMCHAL PRADESH",
            "Kinnaur": "HIMCHAL PRADESH",
            "Lahul": "HIMCHAL PRADESH",
            "Sirmaur": "HIMCHAL PRADESH",
            "Kangra": "HIMCHAL PRADESH",
            "Chamba": "HIMCHAL PRADESH",
            "Himachal": "HIMCHAL PRADESH",
            "शिमला": "HIMCHAL PRADESH",
            "कुल्लू": "HIMCHAL PRADESH",
            "लाहौल": "HIMCHAL PRADESH",
            "सिरमौर": "HIMCHAL PRADESH",
            "कांगड़ा": "HIMCHAL PRADESH",
            "हिमाचल": "HIMCHAL PRADESH",
            "district kangra": "HIMCHAL PRADESH",
            "DISTRICT KANGRA": "HIMCHAL PRADESH",
            "District Kangra": "HIMCHAL PRADESH",
            "District kangra": "HIMCHAL PRADESH",
            "district mandi": "HIMCHAL PRADESH",
            "DISTRICT MANDI": "HIMCHAL PRADESH",
            "District Mandi": "HIMCHAL PRADESH",
            "District mandi": "HIMCHAL PRADESH",
            "distt bilaspur himachal pardesh": "HIMCHAL PRADESH",
            "DISTT BILASPUR HIMACHAL PARDESH": "HIMCHAL PRADESH",
            "Distt Bilaspur Himachal Pardesh": "HIMCHAL PRADESH",
            "Distt bilaspur himachal pardesh": "HIMCHAL PRADESH",
            "distt kangra": "HIMCHAL PRADESH",
            "DISTT KANGRA": "HIMCHAL PRADESH",
            "Distt Kangra": "HIMCHAL PRADESH",
            "Distt kangra": "HIMCHAL PRADESH",
            "distt mandi hp": "HIMCHAL PRADESH",
            "DISTT MANDI HP": "HIMCHAL PRADESH",
            "Distt Mandi Hp": "HIMCHAL PRADESH",
            "Distt mandi hp": "HIMCHAL PRADESH",
            "distt shimla": "HIMCHAL PRADESH",
            "DISTT SHIMLA": "HIMCHAL PRADESH",
            "Distt Shimla": "HIMCHAL PRADESH",
            "Distt shimla": "HIMCHAL PRADESH",
            "जिला मंडी हिमाचल प्रदेश": "HIMCHAL PRADESH",

            "JAMMU & KASHMIR": "JAMMU & KASHMIR",
            "JAMMU": "JAMMU & KASHMIR",
            "SAMBA": "JAMMU & KASHMIR",
            "UDHAMPUR": "JAMMU & KASHMIR",
            "REASI": "JAMMU & KASHMIR",
            "RAMBAN": "JAMMU & KASHMIR",
            "KATHUA": "JAMMU & KASHMIR",
            "POONCH": "JAMMU & KASHMIR",
            "SRINAGAR": "JAMMU & KASHMIR",
            "BUDGAM": "JAMMU & KASHMIR",
            "PULWAMA": "JAMMU & KASHMIR",
            "GANDERBAL": "JAMMU & KASHMIR",
            "ANANTHNAG": "JAMMU & KASHMIR",
            "KULGAM": "JAMMU & KASHMIR",
            "SHOPIAN": "JAMMU & KASHMIR",
            "Baramulla": "JAMMU & KASHMIR",
            "Kupwara": "JAMMU & KASHMIR",
            "BANDIPUR": "JAMMU & KASHMIR",
            "Kargil": "JAMMU & KASHMIR",
            "Jammu": "JAMMU & KASHMIR",
            "Kashmir": "JAMMU & KASHMIR",
            "Jammu": "JAMMU & KASHMIR",
            "Samba": "JAMMU & KASHMIR",
            "Udhampur": "JAMMU & KASHMIR",
            "Ramban": "JAMMU & KASHMIR",
            "Kathua": "JAMMU & KASHMIR",
            "Poonch": "JAMMU & KASHMIR",
            "Srinagar": "JAMMU & KASHMIR",
            "Budgam": "JAMMU & KASHMIR",
            "Pulwama": "JAMMU & KASHMIR",
            "Ganderbal": "JAMMU & KASHMIR",
            "Ananthnag": "JAMMU & KASHMIR",
            "Kulgam": "JAMMU & KASHMIR",
            "Shopian": "JAMMU & KASHMIR",
            "Baramulla": "JAMMU & KASHMIR",
            "Kupwara": "JAMMU & KASHMIR",
            "Bandipur": "JAMMU & KASHMIR",
            "Kargil": "JAMMU & KASHMIR",
            "Jammu": "JAMMU & KASHMIR",
            "Kashmir": "JAMMU & KASHMIR",
            "jammu": "JAMMU & KASHMIR",
            "udhampur": "JAMMU & KASHMIR",
            "Reasi": "JAMMU & KASHMIR",
            "kathua": "JAMMU & KASHMIR",
            "poonch": "JAMMU & KASHMIR",
            "srinagar": "JAMMU & KASHMIR",
            "budgam": "JAMMU & KASHMIR",
            "pulwama": "JAMMU & KASHMIR",
            "ganderbal": "JAMMU & KASHMIR",
            "ananthnag": "JAMMU & KASHMIR",
            "kulgam": "JAMMU & KASHMIR",
            "shopian": "JAMMU & KASHMIR",
            "baramulla": "JAMMU & KASHMIR",
            "kupwara": "JAMMU & KASHMIR",
            "bandipur": "JAMMU & KASHMIR",
            "kargil": "JAMMU & KASHMIR",
            "jammu": "JAMMU & KASHMIR",
            "kashmir": "JAMMU & KASHMIR",
            "जम्मू": "JAMMU & KASHMIR",
            "सांबा": "JAMMU & KASHMIR",
            "उधमपुर": "JAMMU & KASHMIR",
            "रियासी": "JAMMU & KASHMIR",
            "रामबन": "JAMMU & KASHMIR",
            "डोडा": "JAMMU & KASHMIR",
            "कठुआ": "JAMMU & KASHMIR",
            "राजौरी": "JAMMU & KASHMIR",
            "श्रीनगर": "JAMMU & KASHMIR",
            "पुलवामा": "JAMMU & KASHMIR",
            "गांदरबल": "JAMMU & KASHMIR",
            "कुलगाम": "JAMMU & KASHMIR",
            "शोपियां": "JAMMU & KASHMIR",
            "बारामूला": "JAMMU & KASHMIR",
            "कुपवाड़ा": "JAMMU & KASHMIR",
            "बांदीपुर": "JAMMU & KASHMIR",
            "कारगिल": "JAMMU & KASHMIR",
            "जम्मू": "JAMMU & KASHMIR",
            "कश्मीर": "JAMMU & KASHMIR",

            "JHARKHAND": "JHARKHAND",
            "SAHIBGANJ": "JHARKHAND",
            "DUMKA": "JHARKHAND",
            "PAKUR": "JHARKHAND",
            "DEOGHAR": "JHARKHAND",
            "GODDA": "JHARKHAND",
            "JAMTARA": "JHARKHAND",
            "GIRIDH": "JHARKHAND",
            "DHANBAD": "JHARKHAND",
            "LATEHAR": "JHARKHAND",
            "BOKARO": "JHARKHAND",
            "KODERMA": "JHARKHAND",
            "HAZARIBAG": "JHARKHAND",
            "Hazaribagh": "JHARKHAND",
            "RANCHI": "JHARKHAND",
            "SINGHBHUM": "JHARKHAND",
            "SERAIKELAKHARSAWAN": "JHARKHAND",
            "SIMDEGA": "JHARKHAND",
            "Lohardaga": "JHARKHAND",
            "Jharkhand": "JHARKHAND",
            "Sahibganj": "JHARKHAND",
            "Dumka": "JHARKHAND",
            "Godda": "JHARKHAND",
            "Jamtara": "JHARKHAND",
            "Giridh": "JHARKHAND",
            "Dhanbad": "JHARKHAND",
            "Palamau": "JHARKHAND",
            "Latehar": "JHARKHAND",
            "Bokaro": "JHARKHAND",
            "Koderma": "JHARKHAND",
            "Hazaribag": "JHARKHAND",
            "Hazaribagh": "JHARKHAND",
            "Ranchi": "JHARKHAND",
            "Singhbhum": "JHARKHAND",
            "Seraikelakharsawan": "JHARKHAND",
            "Simdega": "JHARKHAND",
            "Lohardaga": "JHARKHAND",
            "Jharkhand": "JHARKHAND",
            "sahibganj": "JHARKHAND",
            "dumka": "JHARKHAND",
            "jamtara": "JHARKHAND",
            "giridh": "JHARKHAND",
            "dhanbad": "JHARKHAND",
            "palamau": "JHARKHAND",
            "latehar": "JHARKHAND",
            "bokaro": "JHARKHAND",
            "koderma": "JHARKHAND",
            "hazaribag": "JHARKHAND",
            "hazaribagh": "JHARKHAND",
            "ranchi": "JHARKHAND",
            "singhbhum": "JHARKHAND",
            "seraikelakharsawan": "JHARKHAND",
            "simdega": "JHARKHAND",
            "lohardaga": "JHARKHAND",
            "jharkhand": "JHARKHAND",
            "साहिबगंज": "JHARKHAND",
            "दुमका": "JHARKHAND",
            "पाकुर": "JHARKHAND",
            "देवघर": "JHARKHAND",
            "गोड्डा": "JHARKHAND",
            "जामताड़ा": "JHARKHAND",
            "गिरीडीह": "JHARKHAND",
            "धनबाद": "JHARKHAND",
            "पलामू": "JHARKHAND",
            "गढ़वा": "JHARKHAND",
            "रामगढ़": "JHARKHAND",
            "बोकारो": "JHARKHAND",
            "कोडरमा": "JHARKHAND",
            "हजारीबाग": "JHARKHAND",
            "हजारीबाग": "JHARKHAND",
            "रांची": "JHARKHAND",
            "सिंहभूम": "JHARKHAND",
            "सिमडेगा": "JHARKHAND",
            "झारखंड": "JHARKHAND",
            "dist godda": "JHARKHAND",
            "DIST GODDA": "JHARKHAND",
            "Dist Godda": "JHARKHAND",
            "Dist godda": "JHARKHAND",
            "जीला गिरिडीह": "JHARKHAND",

            "Karnataka": "Karnataka",
            "BENGALURU": "Karnataka",
            "Bangalore": "Karnataka",
            "BENGALURU": "Karnataka",
            "Karnataka": "Karnataka",
            "Bengaluru": "Karnataka",
            "Bangalore": "Karnataka",
            "Bengaluru": "Karnataka",
            "Karnataka": "Karnataka",
            "bengaluru": "Karnataka",
            "bangalore": "Karnataka",
            "bengaluru": "Karnataka",
            "karnataka": "Karnataka",
            "बेंगलुरु": "Karnataka",
            "बैंगलोर": "Karnataka",
            "कर्नाटक": "Karnataka",

            "Kerala": "Kerala",
            "ERNAKULAM": "Kerala",
            "THIRUVANANTHAPURAM": "Kerala",
            "Kerala": "Kerala",
            "Ernakulam": "Kerala",
            "Thiruvananthapuram": "Kerala",
            "Kerala": "Kerala",
            "ernakulam": "Kerala",
            "thiruvananthapuram": "Kerala",
            "kerala": "Kerala",
            "एर्नाकुलम": "Kerala",
            "तिरुवनंतपुरम": "Kerala",
            "केरल": "Kerala",
            "कोच्चि": "Kerala",
            "Kochi": "Kerala",
            "KOCHI": "Kerala",
            "kochi": "Kerala",

            "Lakshadweep": "Lakshadweep",
            "Lakshadweep": "Lakshadweep",
            "लक्षद्वीप": "Lakshadweep",

            "MADHYA PRADESH": "MADHYA PRADESH",
            "KHANDWA": "MADHYA PRADESH",
            "BURHANPUR": "MADHYA PRADESH",
            "KHARGONE": "MADHYA PRADESH",
            "BARWANI": "MADHYA PRADESH",
            "INDORE": "MADHYA PRADESH",
            "DEWAS": "MADHYA PRADESH",
            "UJJAIN": "MADHYA PRADESH",
            "RATLAM": "MADHYA PRADESH",
            "JHABUA": "MADHYA PRADESH",
            "ALIRAJPUR": "MADHYA PRADESH",
            "MANDSAUR": "MADHYA PRADESH",
            "NEEMUCH": "MADHYA PRADESH",
            "BETUL": "MADHYA PRADESH",
            "HOSHANGABAD": "MADHYA PRADESH",
            "NARSINGHPUR": "MADHYA PRADESH",
            "BHOPAL": "MADHYA PRADESH",
            "RAISEN": "MADHYA PRADESH",
            "VIDISHA": "MADHYA PRADESH",
            "SHAJAPUR": "MADHYA PRADESH",
            "AGAR MALWA": "MADHYA PRADESH",
            "SEHORE": "MADHYA PRADESH",
            "DAMOH": "MADHYA PRADESH",
            "CHHATARPUR": "MADHYA PRADESH",
            "PANNA": "MADHYA PRADESH",
            "TIKAMGARH": "MADHYA PRADESH",
            "GWALIOR": "MADHYA PRADESH",
            "DATIA": "MADHYA PRADESH",
            "MORENA": "MADHYA PRADESH",
            "SHEOPUR": "MADHYA PRADESH",
            "BHIND": "MADHYA PRADESH",
            "CHHINDWARA": "MADHYA PRADESH",
            "SEONI": "MADHYA PRADESH",
            "BALAGHAT": "MADHYA PRADESH",
            "MANDLA": "MADHYA PRADESH",
            "DINDORI": "MADHYA PRADESH",
            "JABALPUR": "MADHYA PRADESH",
            "KATNI": "MADHYA PRADESH",
            "SHAHDOL": "MADHYA PRADESH",
            "ANUPPUR": "MADHYA PRADESH",
            "UMARIA": "MADHYA PRADESH",
            "SATNA": "MADHYA PRADESH",
            "REWA": "MADHYA PRADESH",
            "SINGRAULI": "MADHYA PRADESH",
            "Khandwa": "MADHYA PRADESH",
            "Burhanpur": "MADHYA PRADESH",
            "Khargone": "MADHYA PRADESH",
            "Barwani": "MADHYA PRADESH",
            "Indore": "MADHYA PRADESH",
            "Dewas": "MADHYA PRADESH",
            "Ujjain": "MADHYA PRADESH",
            "Ratlam": "MADHYA PRADESH",
            "Jhabua": "MADHYA PRADESH",
            "Alirajpur": "MADHYA PRADESH",
            "Mandsaur": "MADHYA PRADESH",
            "Neemuch": "MADHYA PRADESH",
            "Betul": "MADHYA PRADESH",
            "Hoshangabad": "MADHYA PRADESH",
            "Narsinghpur": "MADHYA PRADESH",
            "Harda": "MADHYA PRADESH",
            "Bhopal": "MADHYA PRADESH",
            "Raisen": "MADHYA PRADESH",
            "Vidisha": "MADHYA PRADESH",
            "Shajapur": "MADHYA PRADESH",
            "Agar Malwa": "MADHYA PRADESH",
            "Rajgarh": "MADHYA PRADESH",
            "Sehore": "MADHYA PRADESH",
            "Damoh": "MADHYA PRADESH",
            "Chhatarpur": "MADHYA PRADESH",
            "Panna": "MADHYA PRADESH",
            "Tikamgarh": "MADHYA PRADESH",
            "खंडवा": "MADHYA PRADESH",
            "बुरहानपुर": "MADHYA PRADESH",
            "खरगोन": "MADHYA PRADESH",
            "बड़वानी": "MADHYA PRADESH",
            "इंदौर": "MADHYA PRADESH",
            "देवास": "MADHYA PRADESH",
            "उज्जैन": "MADHYA PRADESH",
            "रतलाम": "MADHYA PRADESH",
            "झाबुआ": "MADHYA PRADESH",
            "अलीराजपुर": "MADHYA PRADESH",
            "मंदसौर": "MADHYA PRADESH",
            "नीमच": "MADHYA PRADESH",
            "BETUL": "MADHYA PRADESH",
            "होशंगाबाद": "MADHYA PRADESH",
            "नरसिंहपुर": "MADHYA PRADESH",
            "भोपाल": "MADHYA PRADESH",
            "रायसेन": "MADHYA PRADESH",
            "विदिशा": "MADHYA PRADESH",
            "शाजापुर": "MADHYA PRADESH",
            "आगर मालवा": "MADHYA PRADESH",
            "सीहोर": "MADHYA PRADESH",
            "दमोह": "MADHYA PRADESH",
            "टीकमगढ़": "MADHYA PRADESH",
            "ग्वालियर": "MADHYA PRADESH",
            "मुरैना": "MADHYA PRADESH",
            "श्योपुर": "MADHYA PRADESH",
            "छिंदवाड़ा": "MADHYA PRADESH",
            "सिवनी": "MADHYA PRADESH",
            "बालाघाट": "MADHYA PRADESH",
            "जबलपुर": "MADHYA PRADESH",
            "कटनी": "MADHYA PRADESH",
            "शाहडोल": "MADHYA PRADESH",
            "उमरिया": "MADHYA PRADESH",
            "सिंगरौली": "MADHYA PRADESH",
            "मध्य प्रदेश": "MADHYA PRADESH",
            "मध्यप्रदेश": "MADHYA PRADESH",
            "ऊज्जैन": "MADHYA PRADESH",
            "M.P": "MADHYA PRADESH",
            "MADHYA PRADESH": "MADHYA PRADESH",
            "madhya pradesh": "MADHYA PRADESH",
            "Madhya": "MADHYA PRADESH",
            "Shivpuri": "MADHYA PRADESH",
            "Gwalior": "MADHYA PRADESH",
            "Datia": "MADHYA PRADESH",
            "Morena": "MADHYA PRADESH",
            "Sheopur": "MADHYA PRADESH",
            "Bhind": "MADHYA PRADESH",
            "Chhindwara": "MADHYA PRADESH",
            "Balaghat": "MADHYA PRADESH",
            "Jabalpur": "MADHYA PRADESH",
            "Shahdol": "MADHYA PRADESH",
            "Anuppur": "MADHYA PRADESH",
            "Umaria": "MADHYA PRADESH",
            "Satna": "MADHYA PRADESH",
            "Rewa": "MADHYA PRADESH",
            "Singrauli": "MADHYA PRADESH",
            "khandwa": "MADHYA PRADESH",
            "burhanpur": "MADHYA PRADESH",
            "khargone": "MADHYA PRADESH",
            "barwani": "MADHYA PRADESH",
            "indore": "MADHYA PRADESH",
            "dewas": "MADHYA PRADESH",
            "ujjain": "MADHYA PRADESH",
            "ratlam": "MADHYA PRADESH",
            "jhabua": "MADHYA PRADESH",
            "alirajpur": "MADHYA PRADESH",
            "mandsaur": "MADHYA PRADESH",
            "neemuch": "MADHYA PRADESH",
            "betul": "MADHYA PRADESH",
            "hoshangabad": "MADHYA PRADESH",
            "narsinghpur": "MADHYA PRADESH",
            "bhopal": "MADHYA PRADESH",
            "raisen": "MADHYA PRADESH",
            "vidisha": "MADHYA PRADESH",
            "shajapur": "MADHYA PRADESH",
            "agar malwa": "MADHYA PRADESH",
            "sehore": "MADHYA PRADESH",
            "damoh": "MADHYA PRADESH",
            "tikamgarh": "MADHYA PRADESH",
            "gwalior": "MADHYA PRADESH",
            "morena": "MADHYA PRADESH",
            "sheopur": "MADHYA PRADESH",
            "chhindwara": "MADHYA PRADESH",
            "balaghat": "MADHYA PRADESH",
            "mandla": "MADHYA PRADESH",
            "jabalpur": "MADHYA PRADESH",
            "shahdol": "MADHYA PRADESH",
            "anuppur": "MADHYA PRADESH",
            "umaria": "MADHYA PRADESH",
            "satna": "MADHYA PRADESH",
            "singrauli": "MADHYA PRADESH",
            "Gwailiyer": "MADHYA PRADESH",
            "gwailiyer": "MADHYA PRADESH",
            "GWAILIYER": "MADHYA PRADESH",
            "Ujjian": "MADHYA PRADESH",
            "Sagar MP": "MADHYA PRADESH",
            "जिला गुना": "MADHYA PRADESH",
            "जिला शिवपुरी": "MADHYA PRADESH",
            "तहसील खिलचीपुर": "MADHYA PRADESH",
            "जिला राजगढ़ MP": "MADHYA PRADESH",
            "जीला मन्दसौर": "MADHYA PRADESH",
            "Aagar malwa": "MADHYA PRADESH",
            "jila Sehor MP": "MADHYA PRADESH",
            "जिला मन्दंसौर": "MADHYA PRADESH",
            "aagar malwa": "MADHYA PRADESH",
            "AAGAR MALWA": "MADHYA PRADESH",
            "Aagar Malwa": "MADHYA PRADESH",
            "Aagar malwa": "MADHYA PRADESH",
            "जिला मन्दंसौर": "MADHYA PRADESH",
            "जिला राजगढ़ तहसील खिलचीपुर mp": "MADHYA PRADESH",
            "जीला मन्दसौर": "MADHYA PRADESH",
            "district dhar": "MADHYA PRADESH",
            "DISTRICT DHAR": "MADHYA PRADESH",
            "District Dhar": "MADHYA PRADESH",
            "District dhar": "MADHYA PRADESH",
            "jila sehor": "MADHYA PRADESH",
            "JILA SEHOR": "MADHYA PRADESH",
            "Jila Sehor": "MADHYA PRADESH",
            "Jila sehor": "MADHYA PRADESH",

            "MAHARASTRA": "MAHARASTRA",
            "MUMBAI": "MAHARASTRA",
            "PALGHAR": "MAHARASTRA",
            "PUNE": "MAHARASTRA",
            "SATARA": "MAHARASTRA",
            "SOLAPUR": "MAHARASTRA",
            "AHMED NAGAR": "MAHARASTRA",
            "BEED": "MAHARASTRA",
            "OSMANABAD": "MAHARASTRA",
            "LATUR": "MAHARASTRA",
            "Kolhapur": "MAHARASTRA",
            "Sangli": "MAHARASTRA",
            "SINDHUDURG": "MAHARASTRA",
            "NASHIK": "MAHARASTRA",
            "Malegaon": "MAHARASTRA",
            "Jalgaon": "MAHARASTRA",
            "DHULE": "MAHARASTRA",
            "NANDURBAR": "MAHARASTRA",
            "JALNA": "MAHARASTRA",
            "PARBHANI": "MAHARASTRA",
            "HINGOLI": "MAHARASTRA",
            "Nagpur": "MAHARASTRA",
            "CHANDRAPUR": "MAHARASTRA",
            "GADCHIROLI": "MAHARASTRA",
            "GONDIA": "MAHARASTRA",
            "BHANDARA": "MAHARASTRA",
            "WARDHA": "MAHARASTRA",
            "BULDHANA": "MAHARASTRA",
            "AKOLA": "MAHARASTRA",
            "WASHIM": "MAHARASTRA",
            "AMRAVATI": "MAHARASTRA",
            "Yavatmal": "MAHARASTRA",
            "Maharashtra": "MAHARASTRA",
            "Mumbai": "MAHARASTRA",
            "Palghar": "MAHARASTRA",
            "Pune": "MAHARASTRA",
            "Satara": "MAHARASTRA",
            "Solapur": "MAHARASTRA",
            "Ahmed Nagar": "MAHARASTRA",
            "Beed": "MAHARASTRA",
            "Osmanabad": "MAHARASTRA",
            "Latur": "MAHARASTRA",
            "Kolhapur": "MAHARASTRA",
            "Sangli": "MAHARASTRA",
            "Sindhudurg": "MAHARASTRA",
            "Nashik": "MAHARASTRA",
            "Malegaon": "MAHARASTRA",
            "Jalgaon": "MAHARASTRA",
            "Dhule": "MAHARASTRA",
            "Nandurbar": "MAHARASTRA",
            "Jalna": "MAHARASTRA",
            "Parbhani": "MAHARASTRA",
            "Hingoli": "MAHARASTRA",
            "Nagpur": "MAHARASTRA",
            "Chandrapur": "MAHARASTRA",
            "Gadchiroli": "MAHARASTRA",
            "Gondia": "MAHARASTRA",
            "Bhandara": "MAHARASTRA",
            "Wardha": "MAHARASTRA",
            "Buldhana": "MAHARASTRA",
            "Akola": "MAHARASTRA",
            "Washim": "MAHARASTRA",
            "Amravati": "MAHARASTRA",
            "Yavatmal": "MAHARASTRA",
            "Maharashtra": "MAHARASTRA",
            "mumbai": "MAHARASTRA",
            "palghar": "MAHARASTRA",
            "pune": "MAHARASTRA",
            "satara": "MAHARASTRA",
            "solapur": "MAHARASTRA",
            "ahmed nagar": "MAHARASTRA",
            "osmanabad": "MAHARASTRA",
            "latur": "MAHARASTRA",
            "kolhapur": "MAHARASTRA",
            "sangli": "MAHARASTRA",
            "sindhudurg": "MAHARASTRA",
            "nashik": "MAHARASTRA",
            "malegaon": "MAHARASTRA",
            "jalgaon": "MAHARASTRA",
            "dhule": "MAHARASTRA",
            "nandurbar": "MAHARASTRA",
            "jalna": "MAHARASTRA",
            "parbhani": "MAHARASTRA",
            "hingoli": "MAHARASTRA",
            "nagpur": "MAHARASTRA",
            "chandrapur": "MAHARASTRA",
            "gadchiroli": "MAHARASTRA",
            "gondia": "MAHARASTRA",
            "bhandara": "MAHARASTRA",
            "wardha": "MAHARASTRA",
            "buldhana": "MAHARASTRA",
            "akola": "MAHARASTRA",
            "washim": "MAHARASTRA",
            "amravati": "MAHARASTRA",
            "yavatmal": "MAHARASTRA",
            "maharashtra": "MAHARASTRA",
            "मुंबई": "MAHARASTRA",
            "ठाणे": "MAHARASTRA",
            "पुणे": "MAHARASTRA",
            "सोलापुर": "MAHARASTRA",
            "बीड": "MAHARASTRA",
            "उस्मानाबाद": "MAHARASTRA",
            "लातूर": "MAHARASTRA",
            "कोल्हापुर": "MAHARASTRA",
            "सांगली": "MAHARASTRA",
            "सिंधुदुर्ग": "MAHARASTRA",
            "नासिक": "MAHARASTRA",
            "मालेगांव": "MAHARASTRA",
            "जलगांव": "MAHARASTRA",
            "धुले": "MAHARASTRA",
            "नंदुरबार": "MAHARASTRA",
            "परभनी": "MAHARASTRA",
            "हिंगोली": "MAHARASTRA",
            "नागपुर": "MAHARASTRA",
            "चंद्रपुर": "MAHARASTRA",
            "गडचिरोली": "MAHARASTRA",
            "गोंदिया": "MAHARASTRA",
            "भंडारा": "MAHARASTRA",
            "वर्धा": "MAHARASTRA",
            "बुलढाना": "MAHARASTRA",
            "अकोला": "MAHARASTRA",
            "वाशिम": "MAHARASTRA",
            "अमरावती": "MAHARASTRA",
            "यवतमाल": "MAHARASTRA",
            "महाराष्ट्र": "MAHARASTRA",
            "पालघर": "MAHARASTRA",
            "सोलापूर": "MAHARASTRA",
            "अहमद नगर": "MAHARASTRA",
            "ओएसमानाबाद": "MAHARASTRA",
            "कोल्हापूर": "MAHARASTRA",
            "मिरज": "MAHARASTRA",
            "सिंहदुर्ग": "MAHARASTRA",
            "नाशिक": "MAHARASTRA",
            "मालेगाव": "MAHARASTRA",
            "जळगाव": "MAHARASTRA",
            "जालना": "MAHARASTRA",
            "परभणी": "MAHARASTRA",
            "नॅन्डेड": "MAHARASTRA",
            "नागपूर": "MAHARASTRA",
            "चंद्रपूर": "MAHARASTRA",
            "भांडारा": "MAHARASTRA",
            "बुलढाणा": "MAHARASTRA",
            "वॉशिम": "MAHARASTRA",
            "यवतमाळ": "MAHARASTRA",
            "maharastra": "MAHARASTRA",
            "maharastra": "MAHARASTRA",
            "ahmdnagar": "MAHARASTRA",
            "खंडाळा": "MAHARASTRA",
            "पुणे": "MAHARASTRA",
            "मावळ": "MAHARASTRA",
            "सागंली": "MAHARASTRA",
            "कोल्हा पूर": "MAHARASTRA",
            "Jalgoan": "MAHARASTRA",
            "पनहाळा": "MAHARASTRA",
            "अहमदनगर": "MAHARASTRA",
            "सोलपुर": "MAHARASTRA",
            "Buldana": "MAHARASTRA",
            "buldana": "MAHARASTRA",
            "BULDANA": "MAHARASTRA",
            "जि लातुर": "MAHARASTRA",
            "जि हिगोली": "MAHARASTRA",
            "dist Nanded": "MAHARASTRA",
            "BHUSAWAL": "MAHARASTRA",
            "bhusawal": "MAHARASTRA",
            "Bhusawal": "MAHARASTRA",
            "DIST-JALGAON": "MAHARASTRA",
            "dist-jalgaon": "MAHARASTRA",
            "Dist-Jalgaon": "MAHARASTRA",
            "TITWALA EAST": "MAHARASTRA",
            "titwala east": "MAHARASTRA",
            "Titwala East": "MAHARASTRA",
            "VIRAR EAST": "MAHARASTRA",
            "virar east": "MAHARASTRA",
            "Virar East": "MAHARASTRA",
            "जिल्हा सातारा": "MAHARASTRA",
            "जिल्हा सातारा": "MAHARASTRA",
            "नाला सोपारा": "MAHARASTRA",
            "Dist Solapur": "MAHARASTRA",
            "नालासोपारा": "MAHARASTRA",
            "Kopargaon": "MAHARASTRA",
            "जि सातारा": "MAHARASTRA",
            "dist A nagar": "MAHARASTRA",
            "जिल्हा नांदेड": "MAHARASTRA",
            "जिल्हा औरंगाबाद": "MAHARASTRA",
            "At Nanded": "MAHARASTRA",
            "जिल्हा सांगली": "MAHARASTRA",
            "जिल्हा नांदेड": "MAHARASTRA",
            "at nanded": "MAHARASTRA",
            "AT NANDED": "MAHARASTRA",
            "At Nanded": "MAHARASTRA",
            "At nanded": "MAHARASTRA",
            "dist a nagar": "MAHARASTRA",
            "DIST A NAGAR": "MAHARASTRA",
            "Dist A Nagar": "MAHARASTRA",
            "Dist a nagar mh": "MAHARASTRA",
            "dist solapur": "MAHARASTRA",
            "DIST SOLAPUR": "MAHARASTRA",
            "Dist Solapur": "MAHARASTRA",
            "Dist solapur": "MAHARASTRA",
            "dist wardham": "MAHARASTRA",
            "DIST WARDHAM": "MAHARASTRA",
            "Dist Wardham": "MAHARASTRA",
            "Dist wardham": "MAHARASTRA",
            "dist yawatmal": "MAHARASTRA",
            "DIST YAWATMAL": "MAHARASTRA",
            "Dist Yawatmal": "MAHARASTRA",
            "Dist yawatmal": "MAHARASTRA",
            "distt nasik": "MAHARASTRA",
            "DISTT NASIK": "MAHARASTRA",
            "Distt Nasik": "MAHARASTRA",
            "Distt nasik": "MAHARASTRA",
            "dombivali east": "MAHARASTRA",
            "DOMBIVALI EAST": "MAHARASTRA",
            "Dombivali East": "MAHARASTRA",
            "Dombivali east": "MAHARASTRA",
            "kopargaon mh": "MAHARASTRA",
            "KOPARGAON MH": "MAHARASTRA",
            "Kopargaon Mh": "MAHARASTRA",
            "Kopargaon mh": "MAHARASTRA",
            "nallasopara": "MAHARASTRA",
            "NALLASOPARA": "MAHARASTRA",
            "Nallasopara": "MAHARASTRA",
            "Nallasopara": "MAHARASTRA",
            "जिल्हा औरंगाबाद .": "MAHARASTRA",
            "जिल्हा नांदेड": "MAHARASTRA",
            "जिल्हा सांगली": "MAHARASTRA",
            "जि सातारा mh": "MAHARASTRA",

            "TRIPURA": "TRIPURA",
            "Imphal": "TRIPURA",
            "Tripura": "TRIPURA",
            "Manipur": "TRIPURA",
            "इंफाल": "TRIPURA",
            "त्रिपुरा": "TRIPURA",
            "मणिपुर": "TRIPURA",
            "Megalaya": "TRIPURA",

            "Mizoram": "Mizoram",

            "NAGALAND": "NAGALAND",
            "Nagaland": "NAGALAND",
            "nagaland": "NAGALAND",
            "Nagaland": "NAGALAND",

            "ORRISA": "ORRISA",
            "KHORDA": "ORRISA",
            "NAYAGARH": "ORRISA",
            "CUTTACK": "ORRISA",
            "JAJAPUR": "ORRISA",
            "JAGATSINGHAPUR": "ORRISA",
            "KENDRAPARA": "ORRISA",
            "BALESWAR": "ORRISA",
            "BHADRAK": "ORRISA",
            "MAYURBHANJ": "ORRISA",
            "KENDUJHAR": "ORRISA",
            "DHENKANAL": "ORRISA",
            "ANGUL": "ORRISA",
            "GANJAM": "ORRISA",
            "GAJAPATI": "ORRISA",
            "KANDHAMAL": "ORRISA",
            "BOUDH": "ORRISA",
            "KORAPUT": "ORRISA",
            "MALKANGIRI": "ORRISA",
            "NABARANGAPUR": "ORRISA",
            "KALAHANDI": "ORRISA",
            "NUAPADA": "ORRISA",
            "BALANGIR": "ORRISA",
            "SAMBALPUR": "ORRISA",
            "BARGARH": "ORRISA",
            "DEBAGARH": "ORRISA",
            "JHARSUGUDA": "ORRISA",
            "SUNDERGARH": "ORRISA",
            "Odisha": "ORRISA",
            "Khorda": "ORRISA",
            "nayagarh": "ORRISA",
            "cuttack": "ORRISA",
            "jajapur": "ORRISA",
            "jagatsinghapur": "ORRISA",
            "kendrapara": "ORRISA",
            "baleswar": "ORRISA",
            "bhadrak": "ORRISA",
            "mayurbhanj": "ORRISA",
            "kendujhar": "ORRISA",
            "dhenkanal": "ORRISA",
            "angul": "ORRISA",
            "ganjam": "ORRISA",
            "gajapati": "ORRISA",
            "kandhamal": "ORRISA",
            "boudh": "ORRISA",
            "koraput": "ORRISA",
            "malkangiri": "ORRISA",
            "nabarangapur": "ORRISA",
            "rayagada": "ORRISA",
            "kalahandi": "ORRISA",
            "nuapada": "ORRISA",
            "balangir": "ORRISA",
            "sambalpur": "ORRISA",
            "bargarh": "ORRISA",
            "debagarh": "ORRISA",
            "jharsuguda": "ORRISA",
            "sundergarh": "ORRISA",
            "odisha": "ORRISA",
            "Khorda": "ORRISA",
            "Nayagarh": "ORRISA",
            "Cuttack": "ORRISA",
            "Jagatsinghapur": "ORRISA",
            "Kendrapara": "ORRISA",
            "Baleswar": "ORRISA",
            "Bhadrak": "ORRISA",
            "Mayurbhanj": "ORRISA",
            "Kendujhar": "ORRISA",
            "Dhenkanal": "ORRISA",
            "Angul": "ORRISA",
            "Ganjam": "ORRISA",
            "Gajapati": "ORRISA",
            "Kandhamal": "ORRISA",
            "Boudh": "ORRISA",
            "Koraput": "ORRISA",
            "Malkangiri": "ORRISA",
            "Nabarangapur": "ORRISA",
            "Kalahandi": "ORRISA",
            "Nuapada": "ORRISA",
            "Balangir": "ORRISA",
            "Sonapur": "ORRISA",
            "Sambalpur": "ORRISA",
            "Bargarh": "ORRISA",
            "Debagarh": "ORRISA",
            "Jharsuguda": "ORRISA",
            "Sundergarh": "ORRISA",
            "Odisha": "ORRISA",
            "नयागढ़": "ORRISA",
            "कटक": "ORRISA",
            "केंद्रपाड़ा": "ORRISA",
            "बालेश्वर": "ORRISA",
            "भद्रक": "ORRISA",
            "मयूरभंज": "ORRISA",
            "केंदुझार": "ORRISA",
            "ढेंकनाल": "ORRISA",
            "अंगुल": "ORRISA",
            "गंजम": "ORRISA",
            "गजपति": "ORRISA",
            "कंधमाल": "ORRISA",
            "कोरापुट": "ORRISA",
            "मल्कानगिरी": "ORRISA",
            "कालाहांडी": "ORRISA",
            "नुआपाड़ा": "ORRISA",
            "बलांगीर": "ORRISA",
            "संबलपुर": "ORRISA",
            "झारसुगुडा": "ORRISA",
            "सुंदरगढ़": "ORRISA",
            "ओडिशा": "ORRISA",
            "BALANGIR": "ORRISA",
            "balangir": "ORRISA",
            "Balangir": "ORRISA",
            "KENDUJHAR": "ORRISA",
            "kendujhar": "ORRISA",
            "Kendujhar": "ORRISA",
            "Dist Nabarangapur": "ORRISA",
            "po kurlughati": "ORRISA",
            "dist nabarangapur": "ORRISA",
            "DIST NABARANGAPUR": "ORRISA",
            "Dist Nabarangapur": "ORRISA",
            "Dist nabarangapur": "ORRISA",

            "Pondicherry": "Pondicherry",

            "PUNJAB": "PUNJAB",
            "ROPAR": "PUNJAB",
            "MOHALI": "PUNJAB",
            "RUPNAGAR": "PUNJAB",
            "PATIALA": "PUNJAB",
            "FATEHGARH SAHIB": "PUNJAB",
            "LUDHIANA": "PUNJAB",
            "MOGA": "PUNJAB",
            "FIROZPUR": "PUNJAB",
            "AMRITSAR": "PUNJAB",
            "TARN TARAN": "PUNJAB",
            "GURDASPUR": "PUNJAB",
            "PATHANKOT": "PUNJAB",
            "JALANDHAR": "PUNJAB",
            "HOSHIARPUR": "PUNJAB",
            "KAPURTHALA": "PUNJAB",
            "NAWANSHAHR": "PUNJAB",
            "SANGRUR": "PUNJAB",
            "BATHINDA": "PUNJAB",
            "FARIDKOT": "PUNJAB",
            "MUKTSAR": "PUNJAB",
            "MANSA": "PUNJAB",
            "FAZILKA": "PUNJAB",
            "CHANDIGHAR": "PUNJAB",
            "Punjab": "PUNJAB",
            "Ropar": "PUNJAB",
            "mohali": "PUNJAB",
            "patiala": "PUNJAB",
            "fatehgarh sahib": "PUNJAB",
            "ludhiana": "PUNJAB",
            "moga": "PUNJAB",
            "firozpur": "PUNJAB",
            "amritsar": "PUNJAB",
            "tarn taran": "PUNJAB",
            "gurdaspur": "PUNJAB",
            "pathankot": "PUNJAB",
            "jalandhar": "PUNJAB",
            "hoshiarpur": "PUNJAB",
            "kapurthala": "PUNJAB",
            "nawanshahr": "PUNJAB",
            "sangrur": "PUNJAB",
            "bathinda": "PUNJAB",
            "faridkot": "PUNJAB",
            "muktsar": "PUNJAB",
            "mansa": "PUNJAB",
            "fazilka": "PUNJAB",
            "chandighar": "PUNJAB",
            "punjab": "PUNJAB",
            "Ropar": "PUNJAB",
            "Mohali": "PUNJAB",
            "Patiala": "PUNJAB",
            "Fatehgarh Sahib": "PUNJAB",
            "Ludhiana": "PUNJAB",
            "Moga": "PUNJAB",
            "Firozpur": "PUNJAB",
            "Amritsar": "PUNJAB",
            "Tarn Taran": "PUNJAB",
            "Gurdaspur": "PUNJAB",
            "Pathankot": "PUNJAB",
            "Jalandhar": "PUNJAB",
            "Hoshiarpur": "PUNJAB",
            "Kapurthala": "PUNJAB",
            "Nawanshahr": "PUNJAB",
            "Sangrur": "PUNJAB",
            "Bathinda": "PUNJAB",
            "Faridkot": "PUNJAB",
            "Muktsar": "PUNJAB",
            "Mansa": "PUNJAB",
            "Fazilka": "PUNJAB",
            "Chandighar": "PUNJAB",
            "Punjab": "PUNJAB",
            "रोपड़": "PUNJAB",
            "मोहाली": "PUNJAB",
            "पटियाला": "PUNJAB",
            "फतेहगढ़ SAHIB": "PUNJAB",
            "लुधियाना": "PUNJAB",
            "मोगा": "PUNJAB",
            "फिरोजपुर": "PUNJAB",
            "अमृतसर": "PUNJAB",
            "तरन तरन": "PUNJAB",
            "गुरदासपुर": "PUNJAB",
            "पठानकोट": "PUNJAB",
            "जालंधर": "PUNJAB",
            "होशियारपुर": "PUNJAB",
            "कपूरथला": "PUNJAB",
            "नवांशहर": "PUNJAB",
            "बठिंडा": "PUNJAB",
            "फरीदकोट": "PUNJAB",
            "मुक्तसर": "PUNJAB",
            "फाजिल्का": "PUNJAB",
            "पंजाब": "PUNJAB",
            "ਰੋਪੜ": "PUNJAB",
            "ਮੋਹਾਲੀ": "PUNJAB",
            "ਰੂਪਨਗਰ": "PUNJAB",
            "ਪਤਿਤਲਾ": "PUNJAB",
            "ਫਤਿਹਗੜ੍ਹ ਸਾਹਿਬ": "PUNJAB",
            "ਲੁਧਿਆਣਾ": "PUNJAB",
            "ਮੋਗਾ": "PUNJAB",
            "ਫ਼ਿਰੋਜ਼ਪੁਰ": "PUNJAB",
            "ਅਮ੍ਰਿਤਸਰ": "PUNJAB",
            "ਤਰਨ ਤਾਰਨ": "PUNJAB",
            "ਗੁਰਦਾਸਪੁਰ": "PUNJAB",
            "ਪਠਾਨਕੋਟ": "PUNJAB",
            "ਜਲ੍ਹਾਰ": "PUNJAB",
            "ਹੁਸ਼ਿਆਰਪੁਰ": "PUNJAB",
            "ਕਪੂਰਥਲਾ": "PUNJAB",
            "ਨਵਾਂਸ਼ਹਿਰ": "PUNJAB",
            "ਸੰਗਰੂਰ": "PUNJAB",
            "ਬਠਿੰਡਾ": "PUNJAB",
            "ਫਰੀਡਕੋਟ": "PUNJAB",
            "ਮੁਕਤਸਰ": "PUNJAB",
            "ਮਾਨਸਾ": "PUNJAB",
            "ਫਾਜ਼ਿਲਕਾ": "PUNJAB",
            "ਚੰਦਰੀਅਰ": "PUNJAB",
            "ਪੰਜਾਬ": "PUNJAB",
            "CHANDIGHAR": "PUNJAB",
            "Chandigarh": "PUNJAB",
            "chandigarh": "PUNJAB",
            "Ferozpur pb": "PUNJAB",
            "FEROZEPUR CITY": "PUNJAB",
            "ferozepur city": "PUNJAB",
            "Ferozepur City": "PUNJAB",
            "MUKTSARSAHIB": "PUNJAB",
            "muktsarsahib": "PUNJAB",
            "Muktsarsahib": "PUNJAB",
            "Disst Roper": "PUNJAB",
            "Malout": "PUNJAB",
            "MUKTSAR": "PUNJAB",
            "dist Barnala": "PUNJAB",
            "phagwara": "PUNJAB",
            "KAPURTHALA": "PUNJAB",
            "ferozpore Punjab": "PUNJAB",
            "Dist moga": "PUNJAB",
            "Dist Faridkot": "PUNJAB",
            "ਮਾਨਸ਼ਾ": "PUNJAB",
            "DISTT MANSA": "PUNJAB",
            "distt barnala": "PUNJAB",
            "distic fredkot": "PUNJAB",
            "dist barnala": "PUNJAB",
            "dist barnala": "PUNJAB",
            "DIST BARNALA": "PUNJAB",
            "Dist Barnala": "PUNJAB",
            "Dist barnala": "PUNJAB",
            "dist faridkot": "PUNJAB",
            "DIST FARIDKOT": "PUNJAB",
            "Dist Faridkot": "PUNJAB",
            "Dist faridkot": "PUNJAB",
            "dist moga punjab": "PUNJAB",
            "DIST MOGA PUNJAB": "PUNJAB",
            "Dist Moga Punjab": "PUNJAB",
            "Dist moga punjab": "PUNJAB",
            "DISTIC FREDKOT": "PUNJAB",
            "Distic Fredkot": "PUNJAB",
            "Distic fredkot": "PUNJAB",
            "distt barnala": "PUNJAB",
            "DISTT BARNALA": "PUNJAB",
            "Distt Barnala": "PUNJAB",
            "Distt barnala": "PUNJAB",
            "ferozpore punjab": "PUNJAB",
            "FEROZPORE PUNJAB": "PUNJAB",
            "Ferozpore Punjab": "PUNJAB",
            "Ferozpore punjab": "PUNJAB",
            "malout muktsar": "PUNJAB",
            "MALOUT MUKTSAR": "PUNJAB",
            "Malout Muktsar": "PUNJAB",
            "Malout muktsar": "PUNJAB",
            "ਮਾਨਸ਼ਾ": "PUNJAB",
            "phagwara kapurthala": "PUNJAB",
            "PHAGWARA KAPURTHALA": "PUNJAB",
            "Phagwara Kapurthala": "PUNJAB",
            "Phagwara kapurthala": "PUNJAB",
            "distic fredkot": "PUNJAB",

            "RAJASTHAN": "RAJASTHAN",
            "ALWAR": "RAJASTHAN",
            "JAIPUR": "RAJASTHAN",
            "DAUSA": "RAJASTHAN",
            "TONK": "RAJASTHAN",
            "AJMER": "RAJASTHAN",
            "NAGAUR": "RAJASTHAN",
            "RAJSAMAND": "RAJASTHAN",
            "SIROHI": "RAJASTHAN",
            "UDAIPUR": "RAJASTHAN",
            "JALOR": "RAJASTHAN",
            "BHILWARA": "RAJASTHAN",
            "CHITTORGARH": "RAJASTHAN",
            "DUNGARPUR": "RAJASTHAN",
            "BHARATPUR": "RAJASTHAN",
            "KARAULI": "RAJASTHAN",
            "SAWAI MADHOPUR": "RAJASTHAN",
            "BUNDI": "RAJASTHAN",
            "BARAN": "RAJASTHAN",
            "JHALAWAR": "RAJASTHAN",
            "BANSWARA": "RAJASTHAN",
            "DHOLPUR": "RAJASTHAN",
            "CHURU": "RAJASTHAN",
            "SIKAR": "RAJASTHAN",
            "JHUJHUNU": "RAJASTHAN",
            "BIKANER": "RAJASTHAN",
            "SRI GANGANAGAR": "RAJASTHAN",
            "HANUMANGARH": "RAJASTHAN",
            "SRIGANGANAGAR": "RAJASTHAN",
            "JODHPUR": "RAJASTHAN",
            "JAISALMER": "RAJASTHAN",
            "BARMER": "RAJASTHAN",
            "Rajasthan": "RAJASTHAN",
            "Alwar": "RAJASTHAN",
            "Jaipur": "RAJASTHAN",
            "Dausa": "RAJASTHAN",
            "Tonk": "RAJASTHAN",
            "Ajmer": "RAJASTHAN",
            "Nagaur": "RAJASTHAN",
            "Rajsamand": "RAJASTHAN",
            "Sirohi": "RAJASTHAN",
            "Udaipur": "RAJASTHAN",
            "Jalor": "RAJASTHAN",
            "Bhilwara": "RAJASTHAN",
            "Chittorgarh": "RAJASTHAN",
            "Dungarpur": "RAJASTHAN",
            "Bharatpur": "RAJASTHAN",
            "Karauli": "RAJASTHAN",
            "Sawai Madhopur": "RAJASTHAN",
            "Bundi": "RAJASTHAN",
            "Jhalawar": "RAJASTHAN",
            "Banswara": "RAJASTHAN",
            "Dholpur": "RAJASTHAN",
            "Churu": "RAJASTHAN",
            "Sikar": "RAJASTHAN",
            "Jhujhunu": "RAJASTHAN",
            "Bikaner": "RAJASTHAN",
            "Sri Ganganagar": "RAJASTHAN",
            "Hanumangarh": "RAJASTHAN",
            "Sriganganagar": "RAJASTHAN",
            "Jodhpur": "RAJASTHAN",
            "Jaisalmer": "RAJASTHAN",
            "Barmer": "RAJASTHAN",
            "Rajasthan": "RAJASTHAN",
            "alwar": "RAJASTHAN",
            "jaipur": "RAJASTHAN",
            "dausa": "RAJASTHAN",
            "tonk": "RAJASTHAN",
            "ajmer": "RAJASTHAN",
            "nagaur": "RAJASTHAN",
            "rajsamand": "RAJASTHAN",
            "sirohi": "RAJASTHAN",
            "udaipur": "RAJASTHAN",
            "jalor": "RAJASTHAN",
            "bhilwara": "RAJASTHAN",
            "chittorgarh": "RAJASTHAN",
            "dungarpur": "RAJASTHAN",
            "bharatpur": "RAJASTHAN",
            "karauli": "RAJASTHAN",
            "sawai madhopur": "RAJASTHAN",
            "bundi": "RAJASTHAN",
            "baran": "RAJASTHAN",
            "jhalawar": "RAJASTHAN",
            "banswara": "RAJASTHAN",
            "dholpur": "RAJASTHAN",
            "churu": "RAJASTHAN",
            "sikar": "RAJASTHAN",
            "jhujhunu": "RAJASTHAN",
            "bikaner": "RAJASTHAN",
            "sri ganganagar": "RAJASTHAN",
            "hanumangarh": "RAJASTHAN",
            "sriganganagar": "RAJASTHAN",
            "jodhpur": "RAJASTHAN",
            "jaisalmer": "RAJASTHAN",
            "barmer": "RAJASTHAN",
            "rajasthan": "RAJASTHAN",
            "Alwar": "RAJASTHAN",
            "dausa": "RAJASTHAN",
            "tonk": "RAJASTHAN",
            "ajmer": "RAJASTHAN",
            "nagaur": "RAJASTHAN",
            "rajsamand": "RAJASTHAN",
            "sirohi": "RAJASTHAN",
            "udaipur": "RAJASTHAN",
            "bhilwara": "RAJASTHAN",
            "chittorgarh": "RAJASTHAN",
            "dungarpur": "RAJASTHAN",
            "bharatpur": "RAJASTHAN",
            "karauli": "RAJASTHAN",
            "sawai madhopur": "RAJASTHAN",
            "jhalawar": "RAJASTHAN",
            "banswara": "RAJASTHAN",
            "dholpur": "RAJASTHAN",
            "sikar": "RAJASTHAN",
            "jhujhunu": "RAJASTHAN",
            "bikaner": "RAJASTHAN",
            "sri ganganagar": "RAJASTHAN",
            "hanumangarh": "RAJASTHAN",
            "sriganganagar": "RAJASTHAN",
            "jodhpur": "RAJASTHAN",
            "jaisalmer": "RAJASTHAN",
            "barmer": "RAJASTHAN",
            "rajasthan": "RAJASTHAN",
            "जयपुर": "RAJASTHAN",
            "टोंक": "RAJASTHAN",
            "अजमेर": "RAJASTHAN",
            "राजसमंद": "RAJASTHAN",
            "उदयपुर": "RAJASTHAN",
            "भीलवाड़ा": "RAJASTHAN",
            "डूंगरपुर": "RAJASTHAN",
            "करौली": "RAJASTHAN",
            "झालावाड़": "RAJASTHAN",
            "बांसवाड़ा": "RAJASTHAN",
            "धौलपुर": "RAJASTHAN",
            "सीकर": "RAJASTHAN",
            "बीकानेर": "RAJASTHAN",
            "हनुमानगढ़": "RAJASTHAN",
            "श्रीगंगानगर": "RAJASTHAN",
            "जोधपुर": "RAJASTHAN",
            "जैसलमेर": "RAJASTHAN",
            "बाड़मेर": "RAJASTHAN",
            "राजस्थान": "RAJASTHAN",
            "बाडमेर": "RAJASTHAN",
            "नागौर": "RAJASTHAN",
            "जोधपुर": "RAJASTHAN",
            "बीकानेर": "RAJASTHAN",
            "राजस्थान": "RAJASTHAN",
            "jhunjhunu": "RAJASTHAN",
            "Jhunjhunu": "RAJASTHAN",
            "सूरतगढ़ राजस्थान": "RAJASTHAN",
            "जिला श्री गंगानगर": "RAJASTHAN",
            "<335804>": "RAJASTHAN",
            "जिला हनुमानगढ़": "RAJASTHAN",
            "distt dungapur": "RAJASTHAN",
            "जिला अजमेर": "RAJASTHAN",
            "जिला भीलवाडा": "RAJASTHAN",
            "जिला हनुमानगढ़": "RAJASTHAN",
            "जिला अजमेर": "RAJASTHAN",
            "जिला पाली": "RAJASTHAN",
            "distt dungapur": "RAJASTHAN",
            "DISTT DUNGAPUR": "RAJASTHAN",
            "Distt Dungapur": "RAJASTHAN",
            "Distt dungapur": "RAJASTHAN",

            "SIKKIM": "SIKKIM",
            "Dimapur": "SIKKIM",
            "Sikkim": "SIKKIM",

            "TAMIL NADHU": "TAMIL NADHU",
            "CHENNAI": "TAMIL NADHU",
            "PONDICHERRY": "TAMIL NADHU",
            "CUDDALORE": "TAMIL NADHU",
            "ARIYALUR": "TAMIL NADHU",
            "NAGAPATTINAM": "TAMIL NADHU",
            "THANJAVUR": "TAMIL NADHU",
            "TIRUVARUR": "TAMIL NADHU",
            "KARAIKAL": "TAMIL NADHU",
            "PUDUKKOTTAI": "TAMIL NADHU",
            "TIRUCHIRAPPALLI": "TAMIL NADHU",
            "PERAMBALUR": "TAMIL NADHU",
            "TIRUPPUR": "TAMIL NADHU",
            "COIMBATORE": "TAMIL NADHU",
            "NILGIRIS": "TAMIL NADHU",
            "TAMIL NADU": "TAMIL NADHU",
            "chennai": "TAMIL NADHU",
            "pondicherry": "TAMIL NADHU",
            "cuddalore": "TAMIL NADHU",
            "ariyalur": "TAMIL NADHU",
            "nagapattinam": "TAMIL NADHU",
            "Tamil Nadu": "TAMIL NADHU",
            "चेन्नई": "TAMIL NADHU",
            "कांचीपुरम": "TAMIL NADHU",
            "तिरुवल्लुर": "TAMIL NADHU",
            "तिरुवन्नामलाई": "TAMIL NADHU",
            "पांडिचेरी": "TAMIL NADHU",
            "कुड्डालोर": "TAMIL NADHU",
            "अरियालुर": "TAMIL NADHU",
            "नागपट्टिनम": "TAMIL NADHU",
            "तंजावुर": "TAMIL NADHU",
            "कराईकल": "TAMIL NADHU",
            "पुदुक्कोट्टई": "TAMIL NADHU",
            "तिरुचिरापल्ली": "TAMIL NADHU",
            "पेरम्बलुर": "TAMIL NADHU",
            "करूर": "TAMIL NADHU",
            "डिंडीगुल": "TAMIL NADHU",
            "मदुरै": "TAMIL NADHU",
            "विरुधुनगर": "TAMIL NADHU",
            "तिरुनेलवेली": "TAMIL NADHU",
            "तूतीकोरिन": "TAMIL NADHU",
            "कन्याकूमारी": "TAMIL NADHU",
            "शिवगंगा": "TAMIL NADHU",
            "वेल्लोर": "TAMIL NADHU",
            "कृष्णागिरी": "TAMIL NADHU",
            "नमक्कल": "TAMIL NADHU",
            "तिरुपूर": "TAMIL NADHU",
            "कोयंबत्तूर": "TAMIL NADHU",
            "तमिलनाडु": "TAMIL NADHU",

            "TELANGANA": "TELANGANA",
            "HYDERABAD": "TELANGANA",
            "WARANGAL": "TELANGANA",
            "TELANGANA": "TELANGANA",
            "hyderabad": "TELANGANA",
            "warangal": "TELANGANA",
            "peddapalli": "TELANGANA",
            "sircilla": "TELANGANA",
            "jagtial": "TELANGANA",
            "hanamkonda": "TELANGANA",
            "telangana": "TELANGANA",
            "Hyderabad": "TELANGANA",
            "Warangal": "TELANGANA",
            "हैदराबाद": "TELANGANA",
            "विकाराबाद": "TELANGANA",
            "संगारेड्डी": "TELANGANA",
            "तेलंगाना": "TELANGANA",

            "TRIPURA": "TRIPURA",
            "Tripura": "TRIPURA",
            "Agartala ": "TRIPURA",
            "Sepahijal": "TRIPURA",
            "त्रिपुरा": "TRIPURA",
            "उन्नाव": "",

            "UTTAR PRADESH": "UTTAR PRADESH",
            "GHAZIABAD": "UTTAR PRADESH",
            "GAUTAM BUDDHA": "UTTAR PRADESH",
            "Aligarh": "UTTAR PRADESH",
            "HATHRAS": "UTTAR PRADESH",
            "BULANDSHAHR": "UTTAR PRADESH",
            "MAINPURI": "UTTAR PRADESH",
            "FIROZABAD": "UTTAR PRADESH",
            "ETAWAH": "UTTAR PRADESH",
            "AURAIYA": "UTTAR PRADESH",
            "KANPUR DEHAT": "UTTAR PRADESH",
            "MATHURA": "UTTAR PRADESH",
            "FARRUKHABAD": "UTTAR PRADESH",
            "KANNAUJ": "UTTAR PRADESH",
            "UNNAO": "UTTAR PRADESH",
            "CHITRAKOOT": "UTTAR PRADESH",
            "ALLAHABAD": "UTTAR PRADESH",
            "PRAYAGRAJ ALLAHBAD": "UTTAR PRADESH",
            "Prayagraj Allahabad": "UTTAR PRADESH",
            "KAUSHAMBI": "UTTAR PRADESH",
            "FATEHPUR": "UTTAR PRADESH",
            "VARANASI": "UTTAR PRADESH",
            "CHANDAULI": "UTTAR PRADESH",
            "BALLIA": "UTTAR PRADESH",
            "JAUNPUR": "UTTAR PRADESH",
            "SULTANPUR": "UTTAR PRADESH",
            "AZAMGARH": "UTTAR PRADESH",
            "FAIZABAD": "UTTAR PRADESH",
            "BARABANKI": "UTTAR PRADESH",
            "LUCKNOW": "UTTAR PRADESH",
            "AMETHI": "UTTAR PRADESH",
            "RAEBARELI": "UTTAR PRADESH",
            "PRATAPGARH": "UTTAR PRADESH",
            "MIRZAPUR": "UTTAR PRADESH",
            "SONBHADRA": "UTTAR PRADESH",
            "GHAZIPUR": "UTTAR PRADESH",
            "HARDOI": "UTTAR PRADESH",
            "SHAHJAHANPUR": "UTTAR PRADESH",
            "BUDAUN": "UTTAR PRADESH",
            "PILIBHIT": "UTTAR PRADESH",
            "BAREILLY": "UTTAR PRADESH",
            "MORADABAD": "UTTAR PRADESH",
            "SAMBHAL": "UTTAR PRADESH",
            "HAPUR": "UTTAR PRADESH",
            "MEERUT": "UTTAR PRADESH",
            "BIJNOR": "UTTAR PRADESH",
            "SAHARANPUR": "UTTAR PRADESH",
            "BAGHPAT": "UTTAR PRADESH",
            "BAHRAICH": "UTTAR PRADESH",
            "SHRAWASTI": "UTTAR PRADESH",
            "GORAKHPUR": "UTTAR PRADESH",
            "MAHARAJGANJ": "UTTAR PRADESH",
            "MAHRAJGANJ": "UTTAR PRADESH",
            "KUSHI NAGAR": "UTTAR PRADESH",
            "JHANSI": "UTTAR PRADESH",
            "LALITPUR": "UTTAR PRADESH",
            "JALAUN": "UTTAR PRADESH",
            "Ghaziabad": "UTTAR PRADESH",
            "Gautam Buddha": "UTTAR PRADESH",
            "Aligarh": "UTTAR PRADESH",
            "Hathras": "UTTAR PRADESH",
            "Bulandshahr": "UTTAR PRADESH",
            "Mainpuri": "UTTAR PRADESH",
            "Firozabad": "UTTAR PRADESH",
            "Etawah": "UTTAR PRADESH",
            "Auraiya": "UTTAR PRADESH",
            "Etah": "UTTAR PRADESH",
            "Kanpur Dehat": "UTTAR PRADESH",
            "Mathura": "UTTAR PRADESH",
            "Farrukhabad": "UTTAR PRADESH",
            "Kannauj": "UTTAR PRADESH",
            "Unnao": "UTTAR PRADESH",
            "Chitrakoot": "UTTAR PRADESH",
            "Hamirpur": "UTTAR PRADESH",
            "Mahoba": "UTTAR PRADESH",
            "Allahabad": "UTTAR PRADESH",
            "Prayagraj": "UTTAR PRADESH",
            "Allahbad": "UTTAR PRADESH",
            "Prayagraj Allahabad": "UTTAR PRADESH",
            "Kaushambi": "UTTAR PRADESH",
            "Fatehpur": "UTTAR PRADESH",
            "Varanasi": "UTTAR PRADESH",
            "Chandauli": "UTTAR PRADESH",
            "Jaunpur": "UTTAR PRADESH",
            "Sultanpur": "UTTAR PRADESH",
            "Azamgarh": "UTTAR PRADESH",
            "Faizabad": "UTTAR PRADESH",
            "Barabanki": "UTTAR PRADESH",
            "Lucknow": "UTTAR PRADESH",
            "Amethi": "UTTAR PRADESH",
            "Raebareli": "UTTAR PRADESH",
            "Pratapgarh": "UTTAR PRADESH",
            "Mirzapur": "UTTAR PRADESH",
            "Sonbhadra": "UTTAR PRADESH",
            "Ghazipur": "UTTAR PRADESH",
            "Shahjahanpur": "UTTAR PRADESH",
            "Pilibhit": "UTTAR PRADESH",
            "Bareilly": "UTTAR PRADESH",
            "Moradabad": "UTTAR PRADESH",
            "Amroha": "UTTAR PRADESH",
            "Sambhal": "UTTAR PRADESH",
            "Hapur": "UTTAR PRADESH",
            "Meerut": "UTTAR PRADESH",
            "Saharanpur": "UTTAR PRADESH",
            "Bagpat": "UTTAR PRADESH",
            "Baghpat": "UTTAR PRADESH",
            "Sitapur": "UTTAR PRADESH",
            "Gonda": "UTTAR PRADESH",
            "Balrampur": "UTTAR PRADESH",
            "Bahraich": "UTTAR PRADESH",
            "Shrawasti": "UTTAR PRADESH",
            "Gorakhpur": "UTTAR PRADESH",
            "Maharajganj": "UTTAR PRADESH",
            "Mahrajganj": "UTTAR PRADESH",
            "Deoria": "UTTAR PRADESH",
            "Kushi Nagar": "UTTAR PRADESH",
            "Jhansi": "UTTAR PRADESH",
            "Lalitpur": "UTTAR PRADESH",
            "Jalaun": "UTTAR PRADESH",
            "ghaziabad": "UTTAR PRADESH",
            "gautam buddha": "UTTAR PRADESH",
            "aligarh": "UTTAR PRADESH",
            "hathras": "UTTAR PRADESH",
            "bulandshahr": "UTTAR PRADESH",
            "mainpuri": "UTTAR PRADESH",
            "firozabad": "UTTAR PRADESH",
            "etawah": "UTTAR PRADESH",
            "auraiya": "UTTAR PRADESH",
            "kanpur dehat": "UTTAR PRADESH",
            "mathura": "UTTAR PRADESH",
            "farrukhabad": "UTTAR PRADESH",
            "kannauj": "UTTAR PRADESH",
            "unnao": "UTTAR PRADESH",
            "chitrakoot": "UTTAR PRADESH",
            "hamirpur": "UTTAR PRADESH",
            "mahoba": "UTTAR PRADESH",
            "allahabad": "UTTAR PRADESH",
            "prayagraj allahbad": "UTTAR PRADESH",
            "prayagraj allahabad": "UTTAR PRADESH",
            "kaushambi": "UTTAR PRADESH",
            "fatehpur": "UTTAR PRADESH",
            "varanasi": "UTTAR PRADESH",
            "chandauli": "UTTAR PRADESH",
            "ballia": "UTTAR PRADESH",
            "jaunpur": "UTTAR PRADESH",
            "sultanpur": "UTTAR PRADESH",
            "azamgarh": "UTTAR PRADESH",
            "faizabad": "UTTAR PRADESH",
            "barabanki": "UTTAR PRADESH",
            "lucknow": "UTTAR PRADESH",
            "amethi": "UTTAR PRADESH",
            "raebareli": "UTTAR PRADESH",
            "pratapgarh": "UTTAR PRADESH",
            "mirzapur": "UTTAR PRADESH",
            "sonbhadra": "UTTAR PRADESH",
            "ghazipur": "UTTAR PRADESH",
            "hardoi": "UTTAR PRADESH",
            "shahjahanpur": "UTTAR PRADESH",
            "budaun": "UTTAR PRADESH",
            "pilibhit": "UTTAR PRADESH",
            "bareilly": "UTTAR PRADESH",
            "moradabad": "UTTAR PRADESH",
            "sambhal": "UTTAR PRADESH",
            "hapur": "UTTAR PRADESH",
            "meerut": "UTTAR PRADESH",
            "bijnor": "UTTAR PRADESH",
            "saharanpur": "UTTAR PRADESH",
            "bagpat": "UTTAR PRADESH",
            "baghpat": "UTTAR PRADESH",
            "shrawasti": "UTTAR PRADESH",
            "gorakhpur": "UTTAR PRADESH",
            "maharajganj": "UTTAR PRADESH",
            "mahrajganj": "UTTAR PRADESH",
            "deoria": "UTTAR PRADESH",
            "kushi nagar": "UTTAR PRADESH",
            "jhansi": "UTTAR PRADESH",
            "lalitpur": "UTTAR PRADESH",
            "jalaun": "UTTAR PRADESH",
            "गाज़ियाबाद": "UTTAR PRADESH",
            "गौतम बुद्ध": "UTTAR PRADESH",
            "अलीगढ़": "UTTAR PRADESH",
            "हाथरस": "UTTAR PRADESH",
            "बुलंदशहर": "UTTAR PRADESH",
            "मैनपुरी": "UTTAR PRADESH",
            "फिरोजाबाद": "UTTAR PRADESH",
            "इटावा": "UTTAR PRADESH",
            "औरैया": "UTTAR PRADESH",
            "कानपुर": "UTTAR PRADESH",
            "कनपुर देहात": "UTTAR PRADESH",
            "मथुरा": "UTTAR PRADESH",
            "फर्रुखाबाद": "UTTAR PRADESH",
            "कन्नौज": "UTTAR PRADESH",
            "चित्रकूट": "UTTAR PRADESH",
            "महोबा": "UTTAR PRADESH",
            "इलाहाबाद": "UTTAR PRADESH",
            "प्रयागराज": "UTTAR PRADESH",
            "इलाहाबाद": "UTTAR PRADESH",
            "कौशाम्बी": "UTTAR PRADESH",
            "वाराणसी": "UTTAR PRADESH",
            "चंदौली": "UTTAR PRADESH",
            "जौनपुर": "UTTAR PRADESH",
            "सुल्तानपुर": "UTTAR PRADESH",
            "आजमगढ़": "UTTAR PRADESH",
            "फैजाबाद": "UTTAR PRADESH",
            "अम्बेडकर": "UTTAR PRADESH",
            "बाराबंकी": "UTTAR PRADESH",
            "लखनऊ": "UTTAR PRADESH",
            "अमेठी": "UTTAR PRADESH",
            "रायबरेली": "UTTAR PRADESH",
            "प्रतापगढ़": "UTTAR PRADESH",
            "मिर्जापुर": "UTTAR PRADESH",
            "सोनभद्र": "UTTAR PRADESH",
            "गाजीपुर": "UTTAR PRADESH",
            "हरदोई": "UTTAR PRADESH",
            "शाहजहांपुर": "UTTAR PRADESH",
            "पीलीभीत": "UTTAR PRADESH",
            "मुरादाबाद": "UTTAR PRADESH",
            "अमरोहा": "UTTAR PRADESH",
            "FIROJABAD": "UTTAR PRADESH",
            "Firojabad": "UTTAR PRADESH",
            "firojabad": "UTTAR PRADESH",
            "संभल": "UTTAR PRADESH",
            "हापुड़": "UTTAR PRADESH",
            "मेरठ": "UTTAR PRADESH",
            "बिजनौर": "UTTAR PRADESH",
            "सहारनपुर": "UTTAR PRADESH",
            "बागपत": "UTTAR PRADESH",
            "सीतापुर": "UTTAR PRADESH",
            "गोंडा": "UTTAR PRADESH",
            "बहराइच": "UTTAR PRADESH",
            "श्रावस्ती": "UTTAR PRADESH",
            "महाराजगंज": "UTTAR PRADESH",
            "आगरा": "UTTAR PRADESH",
            "झांसी": "UTTAR PRADESH",
            "जालौन": "UTTAR PRADESH",
            "उत्तर प्रदेश": "UTTAR PRADESH",
            "प्रयागराज": "UTTAR PRADESH",
            "Sant Kabir Nagar": "UTTAR PRADESH",
            "उ प्र": "UTTAR PRADESH",
            "Bulandshahar": "UTTAR PRADESH",
            "BULANDSHAR": "UTTAR PRADESH",
            "bulandshahar": "UTTAR PRADESH",
            "Kanpur Nager": "UTTAR PRADESH",
            "बुलंदशहर": "UTTAR PRADESH",
            "FATEHPUR UP": "UTTAR PRADESH",
            "Lakhimpur Up": "UTTAR PRADESH",
            "fatehpur up": "UTTAR PRADESH",
            "बांदा यूपी": "UTTAR PRADESH",
            "banda up": "UTTAR PRADESH",
            "Fatehpur Up": "UTTAR PRADESH",
            "greater Noida": "UTTAR PRADESH",
            "GREATER NOIDA": "UTTAR PRADESH",
            "Greater Noida": "UTTAR PRADESH",
            "noida gautambudh nagar": "UTTAR PRADESH",
            "ambedkar nagar up": "UTTAR PRADESH",
            "Dist Agra": "UTTAR PRADESH",
            "jila azamghar": "UTTAR PRADESH",
            "Agra U P": "UTTAR PRADESH",
            "alambagh lko": "UTTAR PRADESH",
            "Alambagh Lko": "UTTAR PRADESH",
            "ALAMBAGH LKO": "UTTAR PRADESH",
            "distt-pryagraj": "UTTAR PRADESH",
            "Distt-Pryagraj": "UTTAR PRADESH",
            "DISTT-PRYAGRAJ": "UTTAR PRADESH",
            "NOIDA UP": "UTTAR PRADESH",
            "noida up": "UTTAR PRADESH",
            "Noida Up": "UTTAR PRADESH",
            "Jila gonda": "UTTAR PRADESH",
            "चन्दौली उतर प्रदेश": "UTTAR PRADESH",
            "post mittoopur": "UTTAR PRADESH",
            "चन्दौली उतर प्रदेश": "UTTAR PRADESH",
            "चन्दौली उतर प्रदेश": "UTTAR PRADESH",
            "district Muradabad": "UTTAR PRADESH",
            "noida": "UTTAR PRADESH",
            "district lakhimpur khir i": "UTTAR PRADESH",
            "gaziyabad": "UTTAR PRADESH",
            "distic pilibhit": "UTTAR PRADESH",
            "Allahabad Uttar Pradesh": "UTTAR PRADESH",
            "Jila Shamli": "UTTAR PRADESH",
            "shajhahanpur": "UTTAR PRADESH",
            "noida": "UTTAR PRADESH",
            "NOIDA": "UTTAR PRADESH",
            "Noida": "UTTAR PRADESH",
            "noida": "UTTAR PRADESH",
            "allahabad uttar pradesh": "UTTAR PRADESH",
            "ALLAHABAD UTTAR PRADESH": "UTTAR PRADESH",
            "Allahabad Uttar Pradesh": "UTTAR PRADESH",
            "Allahabad uttar pradesh": "UTTAR PRADESH",
            "district lakhimpur khir i": "UTTAR PRADESH",
            "DISTRICT LAKHIMPUR KHIR I": "UTTAR PRADESH",
            "District Lakhimpur Khir I": "UTTAR PRADESH",
            "District lakhimpur khir i": "UTTAR PRADESH",
            "gaziyabad": "UTTAR PRADESH",
            "GAZIYABAD": "UTTAR PRADESH",
            "Gaziyabad": "UTTAR PRADESH",
            "Gaziyabad": "UTTAR PRADESH",
            "jila gonda": "UTTAR PRADESH",
            "JILA GONDA": "UTTAR PRADESH",
            "Jila Gonda": "UTTAR PRADESH",
            "Jila gonda": "UTTAR PRADESH",
            "jila shamli": "UTTAR PRADESH",
            "JILA SHAMLI": "UTTAR PRADESH",
            "Jila Shamli": "UTTAR PRADESH",
            "Jila shamli": "UTTAR PRADESH",
            "post mittoopur": "UTTAR PRADESH",
            "POST MITTOOPUR": "UTTAR PRADESH",
            "Post Mittoopur": "UTTAR PRADESH",
            "Post mittoopur": "UTTAR PRADESH",
            "shajhahanpur": "UTTAR PRADESH",
            "SHAJHAHANPUR": "UTTAR PRADESH",
            "Shajhahanpur": "UTTAR PRADESH",
            "Shajhahanpur": "UTTAR PRADESH",
            "distic pilibhit": "UTTAR PRADESH",
            "DISTIC PILIBHIT": "UTTAR PRADESH",
            "Distic Pilibhit": "UTTAR PRADESH",
            "Distic pilibhit": "UTTAR PRADESH",

            "UTTRAKHAND": "UTTRAKHAND",
            "NAINITAL": "UTTRAKHAND",
            "UDHAM SINGH NAGAR": "UTTRAKHAND",
            "GARHWAL": "UTTRAKHAND",
            "RUDRAPRAYAG": "UTTRAKHAND",
            "CHAMOLI": "UTTRAKHAND",
            "HARIDWAR": "UTTRAKHAND",
            "DEHRADUN": "UTTRAKHAND",
            "UTTARKASHI": "UTTRAKHAND",
            "CHAMPAWAT": "UTTRAKHAND",
            "PITHORAGARH": "UTTRAKHAND",
            "ALMORA": "UTTRAKHAND",
            "BAGESHWAR": "UTTRAKHAND",
            "Uttarakhand": "UTTRAKHAND",
            "Nainital": "UTTRAKHAND",
            "Udham": "UTTRAKHAND",
            "Garhwal": "UTTRAKHAND",
            "Rudraprayag": "UTTRAKHAND",
            "Chamoli": "UTTRAKHAND",
            "Haridwar": "UTTRAKHAND",
            "Dehradun": "UTTRAKHAND",
            "Uttarkashi": "UTTRAKHAND",
            "Champawat": "UTTRAKHAND",
            "Pithoragarh": "UTTRAKHAND",
            "Almora": "UTTRAKHAND",
            "Bageshwar": "UTTRAKHAND",
            "Uttarakhand": "UTTRAKHAND",
            "nainital": "UTTRAKHAND",
            "udham": "UTTRAKHAND",
            "garhwal": "UTTRAKHAND",
            "rudraprayag": "UTTRAKHAND",
            "chamoli": "UTTRAKHAND",
            "haridwar": "UTTRAKHAND",
            "dehradun": "UTTRAKHAND",
            "uttarkashi": "UTTRAKHAND",
            "champawat": "UTTRAKHAND",
            "pithoragarh": "UTTRAKHAND",
            "almora": "UTTRAKHAND",
            "bageshwar": "UTTRAKHAND",
            "uttarakhand": "UTTRAKHAND",
            "UTTARAKHAND": "UTTRAKHAND",
            "नैनीताल": "UTTRAKHAND",
            "ऊधम": "UTTRAKHAND",
            "रुद्रप्रयाग": "UTTRAKHAND",
            "चमोली": "UTTRAKHAND",
            "हरिद्वार": "UTTRAKHAND",
            "देहरादून": "UTTRAKHAND",
            "उत्तरकाशी": "UTTRAKHAND",
            "चम्पावत": "UTTRAKHAND",
            "पिथोरागढ़": "UTTRAKHAND",
            "बागेश्वर": "UTTRAKHAND",
            "उत्तराखंड": "UTTRAKHAND",
            "nanital": "UTTRAKHAND",
            "RISHIKESH UTTRAKHAND": "UTTRAKHAND",
            "rishikesh uttrakhand": "UTTRAKHAND",
            "Rishikesh Uttrakhand": "UTTRAKHAND",
            "haldwani": "UTTRAKHAND",
            "mussoorie": "UTTRAKHAND",
            "MUSSOORIE": "UTTRAKHAND",
            "Mussoorie": "UTTRAKHAND",
            "Mussoorie": "UTTRAKHAND",

            "WEST BENGAL": "WEST BENGAL",
            "KOLKATA": "WEST BENGAL",
            "PARGANAS": "WEST BENGAL",
            "HOWRAH": "WEST BENGAL",
            "HOOGHLY": "WEST BENGAL",
            "BARDHAMAN": "WEST BENGAL",
            "MIDNAPORE": "WEST BENGAL",
            "BANKURA": "WEST BENGAL",
            "PURULIYA": "WEST BENGAL",
            "BIRBHUM": "WEST BENGAL",
            "DINAJPUR": "WEST BENGAL",
            "DARJILING": "WEST BENGAL",
            "Darjeeling": "WEST BENGAL",
            "JALPAIGURI": "WEST BENGAL",
            "COOCHBEHAR": "WEST BENGAL",
            "MURSHIDABAD": "WEST BENGAL",
            "Bengal": "WEST BENGAL",
            "Kolkata": "WEST BENGAL",
            "Parganas": "WEST BENGAL",
            "Howrah": "WEST BENGAL",
            "Hooghly": "WEST BENGAL",
            "Bardhaman": "WEST BENGAL",
            "Midnapore": "WEST BENGAL",
            "Bankura": "WEST BENGAL",
            "Puruliya": "WEST BENGAL",
            "Birbhum": "WEST BENGAL",
            "Malda": "WEST BENGAL",
            "Dinajpur": "WEST BENGAL",
            "Darjiling": "WEST BENGAL",
            "Darjeeling": "WEST BENGAL",
            "Jalpaiguri": "WEST BENGAL",
            "Coochbehar": "WEST BENGAL",
            "Murshidabad": "WEST BENGAL",
            "Bengal": "WEST BENGAL",
            "kolkata": "WEST BENGAL",
            "parganas": "WEST BENGAL",
            "howrah": "WEST BENGAL",
            "hooghly": "WEST BENGAL",
            "bardhaman": "WEST BENGAL",
            "midnapore": "WEST BENGAL",
            "bankura": "WEST BENGAL",
            "puruliya": "WEST BENGAL",
            "birbhum": "WEST BENGAL",
            "malda": "WEST BENGAL",
            "dinajpur": "WEST BENGAL",
            "darjiling": "WEST BENGAL",
            "darjeeling": "WEST BENGAL",
            "jalpaiguri": "WEST BENGAL",
            "coochbehar": "WEST BENGAL",
            "murshidabad": "WEST BENGAL",
            "bengal": "WEST BENGAL",
            "कोलकाता": "WEST BENGAL",
            "परगना": "WEST BENGAL",
            "हावड़ा": "WEST BENGAL",
            "हुगली": "WEST BENGAL",
            "बर्धमान": "WEST BENGAL",
            "मिदनापुर": "WEST BENGAL",
            "बांकुड़ा": "WEST BENGAL",
            "पुरुलिया": "WEST BENGAL",
            "बीरभूम": "WEST BENGAL",
            "मालदा": "WEST BENGAL",
            "दिनाजपुर": "WEST BENGAL",
            "दार्जिलिंग": "WEST BENGAL",
            "जलपाईगुड़ी": "WEST BENGAL",
            "कूचबिहार": "WEST BENGAL",
            "सिक्किम": "WEST BENGAL",
            "मुर्शिदाबाद": "WEST BENGAL",
            "बंगाल": "WEST BENGAL",

            "NEPAL": "NEPAL",
            "NEPAL": "NEPAL",
            "nepal": "NEPAL",
            "Nepal": "NEPAL",
            "नेपाल": "NEPAL",

            "BANGLADESH": "BANGLADESH",
            "নেত্রকোনা": "BANGLADESH",
            "Bangladesh": "BANGLADESH",
            "बांग्लादेश": "BANGLADESH"
        }

    def getKeys(self):
        return self.dictionary.keys()

    def getState(self, key):
        return self.dictionary.get(key)

    def getStateFromString(self, address):
        for key in self.getKeys():
            if address.find(key.lower()) != -1:
                return self.dictionary.get(key)
